/**
 * BaseLayer form builder — shared field cards, layout, conditional logic.
 *
 * Consumers (Forms, Blocks) enqueue form-builder-admin and use window.BlFormBuilder.
 * Palette / canvas DnD remains in canvas-builder (window.BlCanvasBuilder).
 */
import {
  formsDragStart,
  formsDragEnd,
  TYPE_KEYS,
  PALETTE_SECTIONS,
  uid,
  el,
  appendSafeHelpHtml,
  t,
  iconMarkup,
  iconEl,
  typeLabel,
  fieldIsActive,
  slugifyName,
  slugifyOption,
  collectFieldNames,
  uniqueFieldName,
  cloneFieldData,
  defaultField,
  readConfig,
  writeConfig,
  flattenFields,
} from './dom.js';
import {
  createWidthControl,
  createHeightControl,
  createMarginControl,
  openFieldWidthModal,
  openLayoutSettingsModal,
  openLayoutDesignModal,
  openSectionDesignModal,
  createCssClassControl,
  serializeRow,
  duplicateFieldCard,
  createFieldCard,
} from './field-card.js';
import {
  equalWidthForCount,
  equalizeColumnRun,
  createColumnCard,
  createSectionCard,
  serializeLayoutRow,
} from './layout.js';
import {
  LOGIC_SOURCE_EXCLUDE,
  operatorsForType,
  operatorNeedsValue,
  operatorLabel,
  normalizeConditionalLogic,
  readConditionalLogicFromDom,
  collectLogicSourceFields,
  createConditionalLogicEditor,
} from './conditional-logic.js';
import { configure, resetConfig, getFieldCardHooks } from './config.js';

export {
  formsDragStart,
  formsDragEnd,
  TYPE_KEYS,
  PALETTE_SECTIONS,
  uid,
  el,
  appendSafeHelpHtml,
  t,
  iconMarkup,
  iconEl,
  typeLabel,
  fieldIsActive,
  slugifyName,
  slugifyOption,
  collectFieldNames,
  uniqueFieldName,
  cloneFieldData,
  defaultField,
  readConfig,
  writeConfig,
  flattenFields,
  createWidthControl,
  createHeightControl,
  createMarginControl,
  openFieldWidthModal,
  openLayoutSettingsModal,
  openLayoutDesignModal,
  openSectionDesignModal,
  createCssClassControl,
  serializeRow,
  duplicateFieldCard,
  createFieldCard,
  equalWidthForCount,
  equalizeColumnRun,
  createColumnCard,
  createSectionCard,
  serializeLayoutRow,
  LOGIC_SOURCE_EXCLUDE,
  operatorsForType,
  operatorNeedsValue,
  operatorLabel,
  normalizeConditionalLogic,
  readConditionalLogicFromDom,
  collectLogicSourceFields,
  createConditionalLogicEditor,
  configure,
  resetConfig,
  getFieldCardHooks,
};

const BlFormBuilder = {
  formsDragStart,
  formsDragEnd,
  TYPE_KEYS,
  PALETTE_SECTIONS,
  uid,
  el,
  appendSafeHelpHtml,
  t,
  iconMarkup,
  iconEl,
  typeLabel,
  fieldIsActive,
  slugifyName,
  slugifyOption,
  collectFieldNames,
  uniqueFieldName,
  cloneFieldData,
  defaultField,
  readConfig,
  writeConfig,
  flattenFields,
  createWidthControl,
  createHeightControl,
  createMarginControl,
  openFieldWidthModal,
  openLayoutSettingsModal,
  openLayoutDesignModal,
  openSectionDesignModal,
  createCssClassControl,
  serializeRow,
  duplicateFieldCard,
  createFieldCard,
  equalWidthForCount,
  equalizeColumnRun,
  createColumnCard,
  createSectionCard,
  serializeLayoutRow,
  LOGIC_SOURCE_EXCLUDE,
  operatorsForType,
  operatorNeedsValue,
  operatorLabel,
  normalizeConditionalLogic,
  readConditionalLogicFromDom,
  collectLogicSourceFields,
  createConditionalLogicEditor,
  configure,
  resetConfig,
  getFieldCardHooks,
};

export default BlFormBuilder;

if (typeof window !== 'undefined') {
  window.BlFormBuilder = BlFormBuilder;
}
