/**
 * Auto-generated by scripts/build-js.mjs — do not edit.
 * Imports every customs/<name>/editor.js so new customs are included automatically.
 */
import '../../../customs/container-margin/editor.js';
import '../../../customs/container-wide/editor.js';
import '../../../customs/inner-padding/editor.js';
import '../../../customs/limit-width/editor.js';
