<?php

defined('ABSPATH') || exit;

/**
 * Bulk test data for installer seed_mode=test.
 *
 * Edit this file to change counts and variants.
 * Relative event dates use PHP strtotime offsets from today (site timezone).
 *
 * @return array{
 *   notice: list<string>,
 *   posts: list<array<string, mixed>>,
 *   projects: list<array<string, mixed>>,
 *   events: list<array<string, mixed>>
 * }
 */
return [
	'notice' => [
		'30 blog posts (featured image / excerpt / title-length variants)',
		'28 projects (same layout variants as posts)',
		'41 events (past, future, timed, cancelled, postponed, recurring, soft-deleted occurrence, trash)',
		'Standard install pages and sample media are always included',
	],
	'posts' => [
	[
		'title' => 'Hi',
		'content' => 'I am a blog post with a short title, featured image, and excerpt.',
		'featured_image' => 'sample-image-1',
		'excerpt' => 'Excerpt for a post with a short title, featured image, and excerpt.',
	],
	[
		'title' => 'News',
		'content' => 'I am a blog post with a short title, featured image, no excerpt.',
		'featured_image' => 'sample-image-2',
	],
	[
		'title' => 'Update',
		'content' => 'I am a blog post with a short title, no featured image, with excerpt.',
		'featured_image' => false,
		'excerpt' => 'Excerpt for a post with a short title, no featured image, with excerpt.',
	],
	[
		'title' => 'Note',
		'content' => 'I am a blog post with a short title, no featured image, no excerpt.',
		'featured_image' => false,
	],
	[
		'title' => 'A normal length blog post title for the archive',
		'content' => 'I am a blog post with a normal title, featured image, and excerpt.',
		'featured_image' => 'sample-image-5',
		'excerpt' => 'Excerpt for a post with a normal title, featured image, and excerpt.',
	],
	[
		'title' => 'Another normal blog post title about the theme',
		'content' => 'I am a blog post with a normal title, featured image, no excerpt.',
		'featured_image' => 'sample-image-1',
	],
	[
		'title' => 'Regular post title without a featured image today',
		'content' => 'I am a blog post with a normal title, no featured image, with excerpt.',
		'featured_image' => false,
		'excerpt' => 'Excerpt for a post with a normal title, no featured image, with excerpt.',
	],
	[
		'title' => 'Plain normal title and no extras at all here',
		'content' => 'I am a blog post with a normal title, no featured image, no excerpt.',
		'featured_image' => false,
	],
	[
		'title' => 'This is a deliberately very long blog post title that should wrap across multiple lines in archive cards and list views',
		'content' => 'I am a blog post with a long title, featured image, and excerpt.',
		'featured_image' => 'sample-image-4',
		'excerpt' => 'Excerpt for a post with a long title, featured image, and excerpt.',
	],
	[
		'title' => 'Another extremely long title used to stress-test how headlines behave in grids, lists, and single templates without truncating awkwardly',
		'content' => 'I am a blog post with a long title, featured image, no excerpt.',
		'featured_image' => 'sample-image-5',
	],
	[
		'title' => 'Yet another long headline without an image so we can compare spacing when the media column is missing from the layout entirely',
		'content' => 'I am a blog post with a long title, no featured image, with excerpt.',
		'featured_image' => false,
		'excerpt' => 'Excerpt for a post with a long title, no featured image, with excerpt.',
	],
	[
		'title' => 'Long title, no image, and no excerpt — the leanest long-title case for layout and typography checks in the blog archive',
		'content' => 'I am a blog post with a long title, no featured image, no excerpt.',
		'featured_image' => false,
	],
	[
		'title' => 'Hi (13)',
		'content' => 'I am a blog post with a short title, featured image, and excerpt.',
		'featured_image' => 'sample-image-3',
		'excerpt' => 'Excerpt for a post with a short title, featured image, and excerpt.',
	],
	[
		'title' => 'News (14)',
		'content' => 'I am a blog post with a short title, featured image, no excerpt.',
		'featured_image' => 'sample-image-4',
	],
	[
		'title' => 'Update (15)',
		'content' => 'I am a blog post with a short title, no featured image, with excerpt.',
		'featured_image' => false,
		'excerpt' => 'Excerpt for a post with a short title, no featured image, with excerpt.',
	],
	[
		'title' => 'Note (16)',
		'content' => 'I am a blog post with a short title, no featured image, no excerpt.',
		'featured_image' => false,
	],
	[
		'title' => 'A normal length blog post title for the archive (17)',
		'content' => 'I am a blog post with a normal title, featured image, and excerpt.',
		'featured_image' => 'sample-image-2',
		'excerpt' => 'Excerpt for a post with a normal title, featured image, and excerpt.',
	],
	[
		'title' => 'Another normal blog post title about the theme (18)',
		'content' => 'I am a blog post with a normal title, featured image, no excerpt.',
		'featured_image' => 'sample-image-3',
	],
	[
		'title' => 'Regular post title without a featured image today (19)',
		'content' => 'I am a blog post with a normal title, no featured image, with excerpt.',
		'featured_image' => false,
		'excerpt' => 'Excerpt for a post with a normal title, no featured image, with excerpt.',
	],
	[
		'title' => 'Plain normal title and no extras at all here (20)',
		'content' => 'I am a blog post with a normal title, no featured image, no excerpt.',
		'featured_image' => false,
	],
	[
		'title' => 'This is a deliberately very long blog post title that should wrap across multiple lines in archive cards and list views (21)',
		'content' => 'I am a blog post with a long title, featured image, and excerpt.',
		'featured_image' => 'sample-image-1',
		'excerpt' => 'Excerpt for a post with a long title, featured image, and excerpt.',
	],
	[
		'title' => 'Another extremely long title used to stress-test how headlines behave in grids, lists, and single templates without truncating awkwardly (22)',
		'content' => 'I am a blog post with a long title, featured image, no excerpt.',
		'featured_image' => 'sample-image-2',
	],
	[
		'title' => 'Yet another long headline without an image so we can compare spacing when the media column is missing from the layout entirely (23)',
		'content' => 'I am a blog post with a long title, no featured image, with excerpt.',
		'featured_image' => false,
		'excerpt' => 'Excerpt for a post with a long title, no featured image, with excerpt.',
	],
	[
		'title' => 'Long title, no image, and no excerpt — the leanest long-title case for layout and typography checks in the blog archive (24)',
		'content' => 'I am a blog post with a long title, no featured image, no excerpt.',
		'featured_image' => false,
	],
	[
		'title' => 'Hi (25)',
		'content' => 'I am a blog post with a short title, featured image, and excerpt.',
		'featured_image' => 'sample-image-5',
		'excerpt' => 'Excerpt for a post with a short title, featured image, and excerpt.',
	],
	[
		'title' => 'News (26)',
		'content' => 'I am a blog post with a short title, featured image, no excerpt.',
		'featured_image' => 'sample-image-1',
	],
	[
		'title' => 'Update (27)',
		'content' => 'I am a blog post with a short title, no featured image, with excerpt.',
		'featured_image' => false,
		'excerpt' => 'Excerpt for a post with a short title, no featured image, with excerpt.',
	],
	[
		'title' => 'Note (28)',
		'content' => 'I am a blog post with a short title, no featured image, no excerpt.',
		'featured_image' => false,
	],
	[
		'title' => 'A normal length blog post title for the archive (29)',
		'content' => 'I am a blog post with a normal title, featured image, and excerpt.',
		'featured_image' => 'sample-image-4',
		'excerpt' => 'Excerpt for a post with a normal title, featured image, and excerpt.',
	],
	[
		'title' => 'Another normal blog post title about the theme (30)',
		'content' => 'I am a blog post with a normal title, featured image, no excerpt.',
		'featured_image' => 'sample-image-5',
	],
	],
	'projects' => [
	[
		'title' => 'Project: Hi',
		'content' => 'I am a project with a short title, featured image, and excerpt.',
		'featured_image' => 'sample-image-1',
		'excerpt' => 'Excerpt for a project with a short title, featured image, and excerpt.',
	],
	[
		'title' => 'Project: News',
		'content' => 'I am a project with a short title, featured image, no excerpt.',
		'featured_image' => 'sample-image-2',
	],
	[
		'title' => 'Project: Update',
		'content' => 'I am a project with a short title, no featured image, with excerpt.',
		'featured_image' => false,
		'excerpt' => 'Excerpt for a project with a short title, no featured image, with excerpt.',
	],
	[
		'title' => 'Project: Note',
		'content' => 'I am a project with a short title, no featured image, no excerpt.',
		'featured_image' => false,
	],
	[
		'title' => 'Project: A normal length blog post title for the archive',
		'content' => 'I am a project with a normal title, featured image, and excerpt.',
		'featured_image' => 'sample-image-5',
		'excerpt' => 'Excerpt for a project with a normal title, featured image, and excerpt.',
	],
	[
		'title' => 'Project: Another normal blog post title about the theme',
		'content' => 'I am a project with a normal title, featured image, no excerpt.',
		'featured_image' => 'sample-image-1',
	],
	[
		'title' => 'Project: Regular post title without a featured image today',
		'content' => 'I am a project with a normal title, no featured image, with excerpt.',
		'featured_image' => false,
		'excerpt' => 'Excerpt for a project with a normal title, no featured image, with excerpt.',
	],
	[
		'title' => 'Project: Plain normal title and no extras at all here',
		'content' => 'I am a project with a normal title, no featured image, no excerpt.',
		'featured_image' => false,
	],
	[
		'title' => 'Project: This is a deliberately very long blog post title that should wrap across multiple lines in archive cards and list views',
		'content' => 'I am a project with a long title, featured image, and excerpt.',
		'featured_image' => 'sample-image-4',
		'excerpt' => 'Excerpt for a project with a long title, featured image, and excerpt.',
	],
	[
		'title' => 'Project: Another extremely long title used to stress-test how headlines behave in grids, lists, and single templates without truncating awkwardly',
		'content' => 'I am a project with a long title, featured image, no excerpt.',
		'featured_image' => 'sample-image-5',
	],
	[
		'title' => 'Project: Yet another long headline without an image so we can compare spacing when the media column is missing from the layout entirely',
		'content' => 'I am a project with a long title, no featured image, with excerpt.',
		'featured_image' => false,
		'excerpt' => 'Excerpt for a project with a long title, no featured image, with excerpt.',
	],
	[
		'title' => 'Project: Long title, no image, and no excerpt — the leanest long-title case for layout and typography checks in the blog archive',
		'content' => 'I am a project with a long title, no featured image, no excerpt.',
		'featured_image' => false,
	],
	[
		'title' => 'Project: Hi (13)',
		'content' => 'I am a project with a short title, featured image, and excerpt.',
		'featured_image' => 'sample-image-3',
		'excerpt' => 'Excerpt for a project with a short title, featured image, and excerpt.',
	],
	[
		'title' => 'Project: News (14)',
		'content' => 'I am a project with a short title, featured image, no excerpt.',
		'featured_image' => 'sample-image-4',
	],
	[
		'title' => 'Project: Update (15)',
		'content' => 'I am a project with a short title, no featured image, with excerpt.',
		'featured_image' => false,
		'excerpt' => 'Excerpt for a project with a short title, no featured image, with excerpt.',
	],
	[
		'title' => 'Project: Note (16)',
		'content' => 'I am a project with a short title, no featured image, no excerpt.',
		'featured_image' => false,
	],
	[
		'title' => 'Project: A normal length blog post title for the archive (17)',
		'content' => 'I am a project with a normal title, featured image, and excerpt.',
		'featured_image' => 'sample-image-2',
		'excerpt' => 'Excerpt for a project with a normal title, featured image, and excerpt.',
	],
	[
		'title' => 'Project: Another normal blog post title about the theme (18)',
		'content' => 'I am a project with a normal title, featured image, no excerpt.',
		'featured_image' => 'sample-image-3',
	],
	[
		'title' => 'Project: Regular post title without a featured image today (19)',
		'content' => 'I am a project with a normal title, no featured image, with excerpt.',
		'featured_image' => false,
		'excerpt' => 'Excerpt for a project with a normal title, no featured image, with excerpt.',
	],
	[
		'title' => 'Project: Plain normal title and no extras at all here (20)',
		'content' => 'I am a project with a normal title, no featured image, no excerpt.',
		'featured_image' => false,
	],
	[
		'title' => 'Project: This is a deliberately very long blog post title that should wrap across multiple lines in archive cards and list views (21)',
		'content' => 'I am a project with a long title, featured image, and excerpt.',
		'featured_image' => 'sample-image-1',
		'excerpt' => 'Excerpt for a project with a long title, featured image, and excerpt.',
	],
	[
		'title' => 'Project: Another extremely long title used to stress-test how headlines behave in grids, lists, and single templates without truncating awkwardly (22)',
		'content' => 'I am a project with a long title, featured image, no excerpt.',
		'featured_image' => 'sample-image-2',
	],
	[
		'title' => 'Project: Yet another long headline without an image so we can compare spacing when the media column is missing from the layout entirely (23)',
		'content' => 'I am a project with a long title, no featured image, with excerpt.',
		'featured_image' => false,
		'excerpt' => 'Excerpt for a project with a long title, no featured image, with excerpt.',
	],
	[
		'title' => 'Project: Long title, no image, and no excerpt — the leanest long-title case for layout and typography checks in the blog archive (24)',
		'content' => 'I am a project with a long title, no featured image, no excerpt.',
		'featured_image' => false,
	],
	[
		'title' => 'Project: Hi (25)',
		'content' => 'I am a project with a short title, featured image, and excerpt.',
		'featured_image' => 'sample-image-5',
		'excerpt' => 'Excerpt for a project with a short title, featured image, and excerpt.',
	],
	[
		'title' => 'Project: News (26)',
		'content' => 'I am a project with a short title, featured image, no excerpt.',
		'featured_image' => 'sample-image-1',
	],
	[
		'title' => 'Project: Update (27)',
		'content' => 'I am a project with a short title, no featured image, with excerpt.',
		'featured_image' => false,
		'excerpt' => 'Excerpt for a project with a short title, no featured image, with excerpt.',
	],
	[
		'title' => 'Project: Note (28)',
		'content' => 'I am a project with a short title, no featured image, no excerpt.',
		'featured_image' => false,
	],
	],
	'events' => [
	[
		'title' => 'Past meetup',
		'content' => 'I am a past all-day event.',
		'start' => '-45 days',
		'end' => '-45 days',
		'featured_image' => 'sample-image-1',
	],
	[
		'title' => 'Past workshop',
		'content' => 'I am a past timed workshop.',
		'start' => '-30 days',
		'end' => '-30 days',
		'start_time' => '09:00',
		'end_time' => '12:00',
		'featured_image' => 'sample-image-2',
		'excerpt' => 'Past timed workshop excerpt.',
	],
	[
		'title' => 'Past multi-day conference',
		'content' => 'I am a past multi-day event.',
		'start' => '-20 days',
		'end' => '-18 days',
	],
	[
		'title' => 'Past evening talk',
		'content' => 'I am a past evening event with times.',
		'start' => '-12 days',
		'end' => '-12 days',
		'start_time' => '18:30',
		'end_time' => '20:00',
	],
	[
		'title' => 'Cancelled past show',
		'content' => 'I am a cancelled past event.',
		'start' => '-8 days',
		'end' => '-8 days',
		'start_time' => '19:00',
		'end_time' => '21:00',
		'status' => 'cancelled',
	],
	[
		'title' => 'Short',
		'content' => 'Past event with a short title.',
		'start' => '-5 days',
		'end' => '-5 days',
	],
	[
		'title' => 'This is a very long past event title used to check wrapping in calendars and archive lists for historical entries',
		'content' => 'Past long title.',
		'start' => '-3 days',
		'end' => '-2 days',
	],
	[
		'title' => 'Ongoing exhibition',
		'content' => 'I am an event that started yesterday and ends tomorrow.',
		'start' => '-1 days',
		'end' => '+1 days',
		'featured_image' => 'sample-image-3',
	],
	[
		'title' => 'Today only',
		'content' => 'I am a same-day event happening today.',
		'start' => '0 days',
		'end' => '0 days',
		'start_time' => '10:00',
		'end_time' => '16:00',
	],
	[
		'title' => 'Today no time',
		'content' => 'I am today all-day without times.',
		'start' => '0 days',
		'end' => '0 days',
	],
	[
		'title' => 'Future kickoff',
		'content' => 'I am a future all-day event.',
		'start' => '+3 days',
		'end' => '+3 days',
		'featured_image' => 'sample-image-4',
		'excerpt' => 'Future kickoff excerpt.',
	],
	[
		'title' => 'Future morning session',
		'content' => 'I am a future timed morning session.',
		'start' => '+5 days',
		'end' => '+5 days',
		'start_time' => '09:30',
		'end_time' => '11:00',
	],
	[
		'title' => 'Future afternoon',
		'content' => 'I am a future afternoon block.',
		'start' => '+7 days',
		'end' => '+7 days',
		'start_time' => '14:00',
		'end_time' => '17:30',
		'featured_image' => 'sample-image-5',
	],
	[
		'title' => 'Future multi-day summit',
		'content' => 'I am a future multi-day summit.',
		'start' => '+10 days',
		'end' => '+12 days',
	],
	[
		'title' => 'Postponed town hall',
		'content' => 'I am a postponed future event.',
		'start' => '+14 days',
		'end' => '+14 days',
		'start_time' => '18:00',
		'end_time' => '19:30',
		'status' => 'postponed',
	],
	[
		'title' => 'Cancelled future gala',
		'content' => 'I am a cancelled future event.',
		'start' => '+16 days',
		'end' => '+16 days',
		'start_time' => '19:00',
		'end_time' => '23:00',
		'featured_image' => 'sample-image-1',
		'status' => 'cancelled',
	],
	[
		'title' => 'Go',
		'content' => 'Future short title.',
		'start' => '+18 days',
		'end' => '+18 days',
		'start_time' => '12:00',
		'end_time' => '13:00',
	],
	[
		'title' => 'An especially long future event title that should wrap in listings, featured cards, and single event headers without clipping',
		'content' => 'Future long title.',
		'start' => '+21 days',
		'end' => '+21 days',
		'start_time' => '15:00',
		'end_time' => '18:00',
	],
	[
		'title' => 'Future no image',
		'content' => 'Future event without featured image.',
		'start' => '+25 days',
		'end' => '+25 days',
	],
	[
		'title' => 'Future with excerpt only',
		'content' => 'Future event with excerpt and no image.',
		'start' => '+28 days',
		'end' => '+28 days',
		'excerpt' => 'Just an excerpt for spacing checks.',
	],
	[
		'title' => 'Late future festival',
		'content' => 'Far future multi-day festival.',
		'start' => '+60 days',
		'end' => '+63 days',
		'featured_image' => 'sample-image-2',
	],
	[
		'title' => 'Far talk',
		'content' => 'Far future timed talk.',
		'start' => '+90 days',
		'end' => '+90 days',
		'start_time' => '11:00',
		'end_time' => '12:00',
	],
	[
		'title' => 'Trashed draft meetup',
		'content' => 'I am a trashed one-off event.',
		'start' => '+4 days',
		'end' => '+4 days',
		'trash' => true,
	],
	[
		'title' => 'Trashed past cleanup',
		'content' => 'I am a trashed past event.',
		'start' => '-15 days',
		'end' => '-15 days',
		'trash' => true,
	],
	[
		'title' => 'Series filler event 1',
		'content' => 'I am filler future event number 1 for volume testing.',
		'start' => '+32 days',
		'end' => '+32 days',
	],
	[
		'title' => 'Series filler event 2',
		'content' => 'I am filler future event number 2 for volume testing.',
		'start' => '+34 days',
		'end' => '+34 days',
		'start_time' => '10:00',
		'end_time' => '11:30',
	],
	[
		'title' => 'Series filler event 3',
		'content' => 'I am filler future event number 3 for volume testing.',
		'start' => '+36 days',
		'end' => '+36 days',
		'featured_image' => 'sample-image-4',
	],
	[
		'title' => 'Series filler event 4',
		'content' => 'I am filler future event number 4 for volume testing.',
		'start' => '+38 days',
		'end' => '+38 days',
		'start_time' => '10:00',
		'end_time' => '11:30',
		'excerpt' => 'Excerpt 4',
	],
	[
		'title' => 'Series filler event 5',
		'content' => 'I am filler future event number 5 for volume testing.',
		'start' => '+40 days',
		'end' => '+40 days',
	],
	[
		'title' => 'Series filler event 6',
		'content' => 'I am filler future event number 6 for volume testing.',
		'start' => '+42 days',
		'end' => '+42 days',
		'start_time' => '10:00',
		'end_time' => '11:30',
		'featured_image' => 'sample-image-2',
	],
	[
		'title' => 'Series filler event 7',
		'content' => 'I am filler future event number 7 for volume testing.',
		'start' => '+44 days',
		'end' => '+44 days',
	],
	[
		'title' => 'Series filler event 8',
		'content' => 'I am filler future event number 8 for volume testing.',
		'start' => '+46 days',
		'end' => '+46 days',
		'start_time' => '10:00',
		'end_time' => '11:30',
		'excerpt' => 'Excerpt 8',
	],
	[
		'title' => 'Series filler event 9',
		'content' => 'I am filler future event number 9 for volume testing.',
		'start' => '+48 days',
		'end' => '+48 days',
		'featured_image' => 'sample-image-5',
	],
	[
		'title' => 'Series filler event 10',
		'content' => 'I am filler future event number 10 for volume testing.',
		'start' => '+50 days',
		'end' => '+50 days',
		'start_time' => '10:00',
		'end_time' => '11:30',
	],
	[
		'title' => 'Series filler event 11',
		'content' => 'I am filler future event number 11 for volume testing.',
		'start' => '+52 days',
		'end' => '+52 days',
	],
	[
		'title' => 'Series filler event 12',
		'content' => 'I am filler future event number 12 for volume testing.',
		'start' => '+54 days',
		'end' => '+54 days',
		'start_time' => '10:00',
		'end_time' => '11:30',
		'featured_image' => 'sample-image-3',
		'excerpt' => 'Excerpt 12',
	],
	[
		'title' => 'Series filler event 13',
		'content' => 'I am filler future event number 13 for volume testing.',
		'start' => '+56 days',
		'end' => '+56 days',
	],
	[
		'title' => 'Series filler event 14',
		'content' => 'I am filler future event number 14 for volume testing.',
		'start' => '+58 days',
		'end' => '+58 days',
		'start_time' => '10:00',
		'end_time' => '11:30',
	],
	[
		'title' => 'Series filler event 15',
		'content' => 'I am filler future event number 15 for volume testing.',
		'start' => '+60 days',
		'end' => '+60 days',
		'featured_image' => 'sample-image-1',
	],
	[
		'title' => 'Weekly team sync',
		'content' => 'I am a weekly recurring event. One occurrence will be soft-deleted.',
		'start' => '+2 days',
		'end' => '+2 days',
		'start_time' => '09:00',
		'end_time' => '09:45',
		'featured_image' => 'sample-image-3',
		'recurrence' => [
			'freq' => 'weekly',
			'interval' => 1,
			'byweekday' => ['mo', 'we'],
			'ends' => 'after',
			'count' => 12,
		],
		'soft_delete_occurrence' => true,
	],
	[
		'title' => 'Monthly community call',
		'content' => 'I am a monthly recurring event.',
		'start' => '+9 days',
		'end' => '+9 days',
		'start_time' => '17:00',
		'end_time' => '18:00',
		'recurrence' => [
			'freq' => 'monthly',
			'interval' => 1,
			'ends' => 'after',
			'count' => 6,
		],
	],
	],
];
