import { readdirSync, existsSync, writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const themeRoot = path.join(__dirname, '..');

const ICONS_DIR = 'icons-theme';
const configPath = path.join(themeRoot, 'config/icons.js');
const iconsAbs = path.join(themeRoot, 'assets', ICONS_DIR);
const cssOutPath = path.join(themeRoot, 'assets/css/icons.css');
const jsonOutPath = path.join(themeRoot, 'assets/icons.generated.json');

const humanize = (slug) =>
  slug.replace(/-/g, ' ').replace(/^\w/, (char) => char.toUpperCase());

async function loadConfig() {
  if (!existsSync(configPath)) {
    return {};
  }

  const module = await import(pathToFileURL(configPath).href + '?t=' + Date.now());
  return module.themeIcons || {};
}

function collectIcons(folderAbs, classPrefix, meta) {
  if (!existsSync(folderAbs)) {
    return [];
  }

  const bases = new Set();
  const fills = new Set();

  for (const file of readdirSync(folderAbs)) {
    if (!file.endsWith('.svg')) {
      continue;
    }

    const name = file.replace(/\.svg$/, '');

    if (name.endsWith('-fill')) {
      fills.add(name.slice(0, -'-fill'.length));
    } else {
      bases.add(name);
    }
  }

  return [...bases].sort().map((base) => {
    const info = (meta && meta[base]) || {};

    return {
      base,
      class: `${classPrefix}-${base}`,
      filename: `${classPrefix}-${base}`,
      label: info.label || humanize(base),
      keywords: Array.isArray(info.keywords) ? info.keywords : [],
      hasFill: fills.has(base)
    };
  });
}

function renderCss(icons) {
  const lines = [
    '/* GENERATED by scripts/build-icons.mjs — do not edit by hand. */',
    `/* Source: assets/${ICONS_DIR}/*.svg (+ config/icons.js) */`,
    ''
  ];

  for (const icon of icons) {
    lines.push(
      `.-icon-${icon.class} { --fs-icon: url('../${ICONS_DIR}/${icon.base}.svg'); }`
    );

    if (icon.hasFill) {
      lines.push(
        `.-icon-${icon.class}-fill { --fs-icon: url('../${ICONS_DIR}/${icon.base}-fill.svg'); }`
      );
    }
  }

  lines.push('');
  return lines.join('\n');
}

function renderJson(category, icons) {
  return {
    slug: category.slug,
    label: category.label,
    icons: icons.map((icon) => ({
      filename: icon.filename,
      label: icon.label,
      keywords: icon.keywords,
      alternatives: icon.hasFill ? ['fill'] : []
    }))
  };
}

async function build() {
  const config = await loadConfig();
  const classPrefix = config.prefix || 'theme';
  const category = config.category || { slug: classPrefix, label: humanize(classPrefix) };
  const meta = config.meta || {};

  const icons = collectIcons(iconsAbs, classPrefix, meta);

  mkdirSync(path.dirname(cssOutPath), { recursive: true });
  mkdirSync(iconsAbs, { recursive: true });

  writeFileSync(cssOutPath, renderCss(icons));
  writeFileSync(jsonOutPath, JSON.stringify(renderJson(category, icons), null, 2) + '\n');

  console.log(
    `\u2714 icons: generated ${icons.length} theme icon(s) from assets/${ICONS_DIR}/`
  );
}

await build();
