<?php

defined('ABSPATH') || exit;

/**
 * Core block name => @wordpress/icons filename (without .svg).
 * Blocks not listed use the block slug after "core/" (e.g. core/group → group.svg).
 */
return [
	'core/accordion-heading' => 'accordion-heading',
	'core/accordion-item' => 'accordion-item',
	'core/accordion-panel' => 'contents',
	'core/archives' => 'archive',
	'core/avatar' => 'comment-author-avatar',
	'core/block' => 'symbol',
	'core/categories' => 'category',
	'core/comment-author-avatar' => 'comment-author-avatar',
	'core/comment-author-name' => 'comment-author-name',
	'core/comment-content' => 'comment-content',
	'core/comment-date' => 'post-date',
	'core/comment-edit-link' => 'comment-edit-link',
	'core/comment-reply-link' => 'comment-reply-link',
	'core/comment-template' => 'layout',
	'core/comments' => 'post-comments',
	'core/comments-pagination' => 'query-pagination',
	'core/comments-pagination-next' => 'query-pagination-next',
	'core/comments-pagination-numbers' => 'query-pagination-numbers',
	'core/comments-pagination-previous' => 'query-pagination-previous',
	'core/comments-title' => 'title',
	'core/footnotes' => 'format-list-numbered',
	'core/form-submission-notification' => 'group',
	'core/freeform' => 'classic',
	'core/latest-comments' => 'comment',
	'core/latest-posts' => 'post-list',
	'core/list-item' => 'list-item',
	'core/loginout' => 'login',
	'core/media-text' => 'media-and-text',
	'core/nextpage' => 'page-break',
	'core/page-list-item' => 'page',
	'core/playlist' => 'audio',
	'core/playlist-track' => 'audio',
	'core/post-author' => 'post-author',
	'core/post-author-biography' => 'post-author',
	'core/post-author-name' => 'post-author',
	'core/post-comment' => 'comment',
	'core/post-comments-count' => 'post-comments-count',
	'core/post-comments-form' => 'post-comments-form',
	'core/post-comments-link' => 'post-comments-count',
	'core/post-content' => 'post-content',
	'core/post-date' => 'post-date',
	'core/post-excerpt' => 'post-excerpt',
	'core/post-featured-image' => 'post-featured-image',
	'core/post-terms' => 'post-categories',
	'core/post-time-to-read' => 'time',
	'core/post-title' => 'title',
	'core/query' => 'loop',
	'core/query-no-results' => 'loop',
	'core/query-pagination' => 'query-pagination',
	'core/query-pagination-next' => 'query-pagination-next',
	'core/query-pagination-numbers' => 'query-pagination-numbers',
	'core/query-pagination-previous' => 'query-pagination-previous',
	'core/query-title' => 'title',
	'core/read-more' => 'link',
	'core/site-logo' => 'site-logo',
	'core/site-title' => 'map-marker',
	'core/social-link' => 'share',
	'core/social-links' => 'share',
	'core/spacer' => 'resize-corner-ne',
	'core/tab-list' => 'tab-list',
	'core/tab-panel' => 'tab-panel',
	'core/tab-panels' => 'contents',
	'core/table' => 'block-table',
	'core/table-of-contents' => 'table-of-contents',
	'core/tag-cloud' => 'tag',
	'core/term-count' => 'term-count',
	'core/term-description' => 'term-description',
	'core/term-name' => 'term-name',
	'core/term-template' => 'layout',
	'core/terms-query' => 'loop',
];
