/**
 * Icon catalog for the reusable icon picker (structure only).
 *
 * Each icon is an object:
 *   {
 *     filename: 'heart',        // assets/icons/<filename>.svg (base/outline)
 *     alternatives: ['fill'],   // extra variants: assets/icons/<filename>-<alt>.svg
 *     keywords: ['like', 'love']// English-only search synonyms
 *   }
 *
 * Human-readable names (per icon) and category labels are translatable and are
 * NOT stored here — they come from PHP via `window.fromscratchIcons`
 * (text domain: fromscratch-icons, see inc/editor-icons.php).
 *
 * The generated class names use the filename (`-icon-heart`, `-icon-heart-fill`)
 * and must stay in sync with the SCSS catalog in src/scss/_icons.scss.
 */
import { themeIconCategory } from './icons.generated';

const builtInCategories = [
  {
    slug: 'navigation',
    icons: [
      { filename: 'home', alternatives: ['fill'], keywords: ['house', 'main', 'start'] },
      { filename: 'menu', alternatives: [], keywords: ['hamburger', 'navigation', 'lines'] },
      { filename: 'more', alternatives: [], keywords: ['ellipsis', 'options', 'dots', 'horizontal'] },
      { filename: 'more-vertical', alternatives: [], keywords: ['ellipsis', 'options', 'kebab', 'dots'] },
      { filename: 'arrow-left-alt', alternatives: [], keywords: ['back', 'previous', 'left', 'alt'] },
      { filename: 'arrow-right-alt', alternatives: [], keywords: ['next', 'forward', 'right', 'alt'] },
      { filename: 'arrow-up-alt', alternatives: [], keywords: ['up', 'upward', 'alt'] },
      { filename: 'arrow-down-alt', alternatives: [], keywords: ['down', 'arrow', 'downward', 'alt', 'scroll'] },
      { filename: 'arrow-left', alternatives: [], keywords: ['back', 'previous', 'left'] },
      { filename: 'arrow-right', alternatives: [], keywords: ['next', 'forward', 'right'] },
      { filename: 'arrow-up', alternatives: [], keywords: ['up', 'upward', 'top', 'north'] },
      { filename: 'arrow-down', alternatives: [], keywords: ['down', 'downward', 'bottom', 'south'] },
      { filename: 'arrow-line-start', alternatives: [], keywords: ['start', 'line', 'arrow', 'first'] },
      { filename: 'arrow-line-end', alternatives: [], keywords: ['end', 'line', 'arrow', 'last'] },
      { filename: 'chevron-left-large', alternatives: [], keywords: ['back', 'previous', 'left', 'big', 'bold'] },
      { filename: 'chevron-right-large', alternatives: [], keywords: ['next', 'forward', 'right', 'big', 'bold'] },
      { filename: 'chevron-left', alternatives: [], keywords: ['back', 'previous', 'left'] },
      { filename: 'chevron-right', alternatives: [], keywords: ['next', 'forward', 'right'] },
      { filename: 'chevron-up', alternatives: [], keywords: ['up', 'collapse', 'less'] },
      { filename: 'chevron-down', alternatives: [], keywords: ['down', 'expand', 'dropdown', 'more'] },
      { filename: 'drop-left', alternatives: [], keywords: ['caret', 'left', 'collapse'] },
      { filename: 'drop-right', alternatives: [], keywords: ['caret', 'right', 'expand'] },
      { filename: 'drop-up', alternatives: [], keywords: ['caret', 'up', 'collapse'] },
      { filename: 'drop-down', alternatives: [], keywords: ['caret', 'down', 'dropdown'] },
      { filename: 'subdirectory-arrow', alternatives: [], keywords: ['return', 'nested', 'enter', 'branch'] },
      { filename: 'arrow-range', alternatives: [], keywords: ['range', 'width', 'distance', 'measure', 'horizontal', 'span'] },
      { filename: 'compare', alternatives: [], keywords: ['versus', 'difference', 'split'] },
      { filename: 'swap-horizontal', alternatives: [], keywords: ['exchange', 'switch', 'transfer', 'arrows'] },
      { filename: 'swap-vertical', alternatives: [], keywords: ['exchange', 'switch', 'reorder', 'arrows'] },
      { filename: 'expand', alternatives: [], keywords: ['enlarge', 'maximize', 'arrows'] },
      { filename: 'collapse', alternatives: [], keywords: ['minimize', 'shrink', 'close', 'inward', 'arrows'] },
      { filename: 'expand-content', alternatives: [], keywords: ['unfold', 'more', 'enlarge', 'open', 'arrows'] },
      { filename: 'collapse-content', alternatives: [], keywords: ['fold', 'less', 'hide', 'minimize', 'arrows'] },
      { filename: 'arrow-outward', alternatives: [], keywords: ['external', 'outward', 'diagonal', 'northeast', 'go to'] },
      { filename: 'open-in-new', alternatives: [], keywords: ['external', 'link', 'window', 'tab'] },
      { filename: 'open-in-new-down', alternatives: [], keywords: ['external', 'link', 'open', 'download', 'down'] },
      { filename: 'hide', alternatives: [], keywords: ['hide', 'invisible', 'concealed', 'off'] },
      { filename: 'pan-zoom', alternatives: [], keywords: ['pan', 'zoom', 'move', 'view', 'map'] },
      { filename: 'shape-up', alternatives: ['fill'], keywords: ['up', 'arrow', 'shape', 'shift', 'arrow-up-thick'] },
      { filename: 'shape-up-stack', alternatives: ['fill'], keywords: ['up', 'arrow', 'shape', 'stack', 'shift'] },
    ],
  },
  {
    slug: 'actions',
    icons: [
      { filename: 'add', alternatives: [], keywords: ['plus', 'new', 'create'] },
      { filename: 'add-circle', alternatives: ['fill'], keywords: ['plus', 'new', 'create'] },
      { filename: 'minus', alternatives: [], keywords: ['remove', 'subtract', 'less'] },
      { filename: 'minus-circle', alternatives: ['fill'], keywords: ['remove', 'subtract', 'delete', 'do not disturb'] },
      { filename: 'checkmark', alternatives: [], keywords: ['check', 'done', 'ok', 'tick', 'confirm'] },
      { filename: 'check-circle', alternatives: ['fill'], keywords: ['done', 'ok', 'success', 'confirm'] },
      { filename: 'close', alternatives: [], keywords: ['x', 'cancel', 'dismiss', 'remove'] },
      { filename: 'cancel', alternatives: ['fill'], keywords: ['close', 'x', 'dismiss', 'stop'] },
      { filename: 'block', alternatives: ['fill'], keywords: ['forbidden', 'ban', 'disable', 'no'] },
      { filename: 'search', alternatives: [], keywords: ['find', 'magnifier', 'lookup'] },
      { filename: 'zoom-in', alternatives: [], keywords: ['magnify', 'plus', 'enlarge'] },
      { filename: 'zoom-out', alternatives: [], keywords: ['magnify', 'minus', 'shrink'] },
      { filename: 'delete', alternatives: ['fill'], keywords: ['trash', 'remove', 'bin'] },
      { filename: 'delete-forever', alternatives: ['fill'], keywords: ['delete', 'trash', 'permanent', 'remove forever'] },
      { filename: 'restore', alternatives: ['fill'], keywords: ['restore', 'recover', 'undelete', 'reset'] },
      { filename: 'save', alternatives: ['fill'], keywords: ['disk', 'store'] },
      { filename: 'save-as', alternatives: ['fill'], keywords: ['save', 'export', 'copy', 'duplicate', 'document'] },
      { filename: 'print', alternatives: ['fill'], keywords: ['printer'] },
      { filename: 'download', alternatives: [], keywords: ['save', 'export', 'arrow'] },
      { filename: 'download-alt', alternatives: ['fill'], keywords: ['save', 'export', 'arrow'] },
      { filename: 'upload', alternatives: [], keywords: ['import', 'send', 'arrow'] },
      { filename: 'upload-alt', alternatives: ['fill'], keywords: ['import', 'send', 'arrow'] },
      { filename: 'upgrade', alternatives: [], keywords: ['improve', 'level up', 'arrow'] },
      { filename: 'signature', alternatives: [], keywords: ['signature', 'sign', 'autograph', 'handwriting'] },
      { filename: 'crop', alternatives: [], keywords: ['trim', 'resize', 'image'] },
      { filename: 'resize', alternatives: [], keywords: ['resize', 'scale', 'dimensions', 'transform'] },
      { filename: 'refresh', alternatives: [], keywords: ['reload', 'update', 'renew'] },
      { filename: 'sync', alternatives: [], keywords: ['refresh', 'update', 'reload', 'arrows'] },
      { filename: 'undo', alternatives: [], keywords: ['back', 'revert', 'arrow'] },
      { filename: 'redo', alternatives: [], keywords: ['forward', 'repeat', 'arrow'] },
      { filename: 'fullscreen', alternatives: [], keywords: ['enlarge', 'maximize', 'expand'] },
      { filename: 'fullscreen-exit', alternatives: [], keywords: ['minimize', 'shrink', 'collapse'] },
      { filename: 'zoom-in-map', alternatives: [], keywords: ['zoom', 'map', 'enlarge', 'magnify'] },
      { filename: 'zoom-out-map', alternatives: [], keywords: ['zoom', 'map', 'shrink', 'overview'] },
      { filename: 'drag', alternatives: [], keywords: ['move', 'reorder', 'handle', 'grab'] },
      { filename: 'drag-handle', alternatives: [], keywords: ['move', 'reorder', 'handle', 'grab'] },
      { filename: 'swipe-left-right', alternatives: ['fill'], keywords: ['swipe', 'gesture', 'horizontal', 'touch'] },
      { filename: 'swipe-up-down', alternatives: ['fill'], keywords: ['swipe', 'gesture', 'vertical', 'touch'] },
      { filename: 'touch', alternatives: ['fill'], keywords: ['tap', 'finger', 'gesture'] },
      { filename: 'click', alternatives: [], keywords: ['tap', 'cursor', 'select'] },
      { filename: 'click-action', alternatives: [], keywords: ['click', 'cursor', 'action', 'mouse'] },
      { filename: 'click-left', alternatives: [], keywords: ['click', 'left', 'mouse', 'button'] },
      { filename: 'click-right', alternatives: [], keywords: ['click', 'right', 'mouse', 'button'] },
    ],
  },
  {
    slug: 'editing',
    icons: [
      { filename: 'edit', alternatives: ['fill'], keywords: ['pencil', 'pen', 'modify', 'change'] },
      { filename: 'edit-square', alternatives: ['fill'], keywords: ['edit', 'pencil', 'square', 'modify'] },
      { filename: 'edit-text', alternatives: ['fill'], keywords: ['pencil', 'write', 'modify'] },
      { filename: 'edit-document', alternatives: ['fill'], keywords: ['pencil', 'write', 'file'] },
      { filename: 'document', alternatives: ['fill'], keywords: ['file', 'page', 'paper'] },
      { filename: 'document-text', alternatives: ['fill'], keywords: ['file', 'page', 'text'] },
      { filename: 'document-person', alternatives: ['fill'], keywords: ['file', 'person', 'profile', 'resume', 'cv'] },
      { filename: 'document-scan', alternatives: ['fill'], keywords: ['scan', 'document', 'ocr', 'capture'] },
      { filename: 'article', alternatives: ['fill'], keywords: ['post', 'document', 'news', 'text'] },
      { filename: 'compare-text', alternatives: ['fill'], keywords: ['compare', 'text', 'diff', 'versus'] },
      { filename: 'palette', alternatives: ['fill'], keywords: ['color', 'design', 'art', 'theme', 'paint'] },
      { filename: 'colorize', alternatives: ['fill'], keywords: ['color', 'paint', 'eyedropper', 'design', 'palette'] },
      { filename: 'copy', alternatives: ['fill'], keywords: ['duplicate', 'clipboard'] },
      { filename: 'clipboard', alternatives: [], keywords: ['paste', 'copy', 'board'] },
      { filename: 'content-cut', alternatives: [], keywords: ['cut', 'scissors', 'trim', 'clip'] },
      { filename: 'text', alternatives: [], keywords: ['text', 'typography', 'letter', 'font', 'content'] },
      { filename: 'list', alternatives: [], keywords: ['lines', 'items', 'menu'] },
      { filename: 'abc', alternatives: [], keywords: ['letters', 'alphabet', 'text', 'characters', 'spelling'] },
      { filename: '123', alternatives: [], keywords: ['numbers', 'digits', 'numeric', 'count'] },
      { filename: 'symbols', alternatives: [], keywords: ['symbols', 'special characters', 'typography', 'glyph'] },
      { filename: 'language', alternatives: [], keywords: ['globe', 'locale', 'translate', 'international'] },
      { filename: 'translate', alternatives: [], keywords: ['language', 'localize', 'translation'] },
      { filename: 'code', alternatives: [], keywords: ['code', 'developer', 'markup'] },
      { filename: 'code-slash', alternatives: [], keywords: ['code', 'developer', 'slash', 'programming'] },
      { filename: 'book', alternatives: ['fill'], keywords: ['read', 'library', 'publication'] },
      { filename: 'book-open', alternatives: ['fill'], keywords: ['read', 'open', 'library', 'publication'] },
    ],
  },
  {
    slug: 'rich-text',
    icons: [
      { filename: 'text-format', alternatives: [], keywords: ['text', 'format', 'typography', 'font', 'wysiwyg'] },
      { filename: 'bold', alternatives: [], keywords: ['bold', 'strong', 'weight', 'typography'] },
      { filename: 'italic', alternatives: [], keywords: ['italic', 'emphasis', 'slant', 'typography'] },
      { filename: 'underlined', alternatives: [], keywords: ['underline', 'typography', 'text'] },
      { filename: 'strikethrough', alternatives: ['fill'], keywords: ['strikethrough', 'strike', 'cross out', 'typography'] },
      { filename: 'align-left', alternatives: [], keywords: ['align', 'left', 'text', 'paragraph'] },
      { filename: 'align-center', alternatives: [], keywords: ['align', 'center', 'text', 'paragraph'] },
      { filename: 'align-right', alternatives: [], keywords: ['align', 'right', 'text', 'paragraph'] },
      { filename: 'align-justify', alternatives: [], keywords: ['align', 'justify', 'text', 'paragraph'] },
      { filename: 'list-bulleted', alternatives: [], keywords: ['list', 'bulleted', 'unordered', 'ul', 'list-bullet'] },
      { filename: 'list-numbered', alternatives: [], keywords: ['list', 'numbered', 'ordered', 'ol', 'list-number'] },
      { filename: 'checklist', alternatives: [], keywords: ['checklist', 'todo', 'tasks', 'list'] },
      { filename: 'indent-decrease', alternatives: [], keywords: ['indent', 'decrease', 'outdent', 'margin'] },
      { filename: 'indent-increase', alternatives: [], keywords: ['indent', 'increase', 'margin'] },
      { filename: 'line-spacing', alternatives: [], keywords: ['line', 'spacing', 'leading', 'paragraph'] },
      { filename: 'letter-spacing', alternatives: ['fill'], keywords: ['letter', 'spacing', 'tracking', 'typography'] },
      { filename: 'format-size', alternatives: ['fill'], keywords: ['font', 'size', 'text', 'typography'] },
      { filename: 'colors', alternatives: [], keywords: ['colors', 'palette', 'swatches', 'design'] },
      { filename: 'color-fill', alternatives: [], keywords: ['highlight', 'fill', 'background', 'color'] },
      { filename: 'color-text', alternatives: [], keywords: ['text', 'color', 'font', 'typography'] },
      { filename: 'border-color', alternatives: ['fill'], keywords: ['border', 'color', 'outline', 'pen'] },
      { filename: 'color-reset', alternatives: ['fill'], keywords: ['reset', 'clear', 'color', 'formatting'] },
      { filename: 'link', alternatives: [], keywords: ['url', 'chain', 'hyperlink', 'anchor'] },
      { filename: 'link-off', alternatives: [], keywords: ['unlink', 'broken', 'remove', 'hyperlink'] },
      { filename: 'image-left', alternatives: ['fill'], keywords: ['align', 'wrap', 'float', 'text', 'image'] },
      { filename: 'image-right', alternatives: ['fill'], keywords: ['align', 'wrap', 'float', 'text', 'image'] },
      { filename: 'image-front', alternatives: ['fill'], keywords: ['align', 'inline', 'image', 'text', 'wrap'] },
      { filename: 'paragraph', alternatives: [], keywords: ['text', 'block', 'typography', 'content'] },
      { filename: 'quote', alternatives: ['fill'], keywords: ['blockquote', 'citation', 'testimonial'] },
      { filename: 'code-block', alternatives: ['fill'], keywords: ['code', 'block', 'snippet', 'gutenberg'] },
      { filename: 'clear-all', alternatives: [], keywords: ['clear', 'reset', 'formatting', 'remove'] },
    ],
  },
  {
    slug: 'communication',
    icons: [
      { filename: 'chat', alternatives: ['fill'], keywords: ['message', 'bubble', 'comment', 'talk'] },
      { filename: 'chat-dashed', alternatives: [], keywords: ['chat', 'message', 'bubble', 'dashed'] },
      { filename: 'chat-dots', alternatives: ['fill'], keywords: ['message', 'typing', 'bubble'] },
      { filename: 'chat-text', alternatives: ['fill'], keywords: ['message', 'comment', 'bubble'] },
      { filename: 'chat-edit', alternatives: ['fill'], keywords: ['chat', 'edit', 'review', 'feedback', 'comment', 'rate', 'message'] },
      { filename: 'forum', alternatives: ['fill'], keywords: ['discussion', 'comments', 'community'] },
      { filename: 'mail', alternatives: ['fill'], keywords: ['envelope', 'message', 'email', 'contact'] },
      { filename: 'email-open', alternatives: ['fill'], keywords: ['envelope', 'read', 'message'] },
      { filename: 'email-alt', alternatives: [], keywords: ['envelope', 'message', 'contact'] },
      { filename: 'phone', alternatives: ['fill'], keywords: ['call', 'contact', 'telephone'] },
      { filename: 'send', alternatives: ['fill'], keywords: ['paper plane', 'submit', 'message'] },
      { filename: 'attachment', alternatives: [], keywords: ['paperclip', 'attach', 'file'] },
    ],
  },
  {
    slug: 'social',
    icons: [
      { filename: 'heart', alternatives: ['fill'], keywords: ['like', 'love', 'favorite'] },
      { filename: 'thumb-up-down', alternatives: ['fill'], keywords: ['vote', 'rating', 'feedback'] },
      { filename: 'thumb-up', alternatives: ['fill'], keywords: ['like', 'approve', 'good', 'vote'] },
      { filename: 'thumb-down', alternatives: ['fill'], keywords: ['dislike', 'disapprove', 'bad', 'vote'] },
      { filename: 'star', alternatives: [], keywords: ['favorite', 'rating', 'bookmark'] },
      { filename: 'star-half', alternatives: [], keywords: ['rating', 'half', 'review'] },
      { filename: 'star-filled', alternatives: [], keywords: ['rating', 'filled', 'review'] },
      { filename: 'stars', alternatives: ['fill'], keywords: ['stars', 'rating', 'hotel', 'class', 'quality', 'review', 'hotel-class'] },
      { filename: 'stars-sparkle', alternatives: ['fill'], keywords: ['rating', 'favorite', 'sparkle', 'review', 'stars'] },
      { filename: 'star-kid', alternatives: ['fill'], keywords: ['kids', 'child', 'favorite', 'rating', 'fun'] },
      { filename: 'star-award', alternatives: ['fill'], keywords: ['award', 'prize', 'achievement', 'badge', 'quality', 'rating'] },
      { filename: 'megaphone', alternatives: ['fill'], keywords: ['announcement', 'marketing', 'promote', 'loud'] },
      { filename: 'bookmark', alternatives: ['fill'], keywords: ['save', 'favorite', 'mark'] },
      { filename: 'bookmark-heart', alternatives: ['fill'], keywords: ['save', 'favorite', 'love', 'bookmark'] },
      { filename: 'bookmark-stacks', alternatives: ['fill'], keywords: ['bookmarks', 'saved', 'collection', 'stack'] },
      { filename: 'smiley', alternatives: [], keywords: ['smiley', 'emoji', 'face', 'mood'] },
      { filename: 'smiley-happy', alternatives: ['fill'], keywords: ['emoji', 'smile', 'positive', 'mood'] },
      { filename: 'smiley-neutral', alternatives: ['fill'], keywords: ['emoji', 'meh', 'mood'] },
      { filename: 'smiley-sad', alternatives: ['fill'], keywords: ['emoji', 'frown', 'negative', 'mood'] },
      { filename: 'share', alternatives: [], keywords: ['network', 'nodes', 'send'] },
      { filename: 'share-social', alternatives: ['fill'], keywords: ['social', 'network', 'send'] },
      { filename: 'rss', alternatives: [], keywords: ['feed', 'subscribe', 'syndication', 'blog'] },
      { filename: 'flag', alternatives: ['fill'], keywords: ['report', 'mark', 'banner'] },
      { filename: 'flag-alt', alternatives: ['fill'], keywords: ['flag', 'report', 'banner', 'alt'] },
      { filename: 'celebration', alternatives: ['fill'], keywords: ['party', 'confetti', 'congrats', 'event', 'success', 'festive'] },
      { filename: 'cheer', alternatives: ['fill'], keywords: ['cheer', 'high five', 'celebrate', 'hands', 'teamwork'] },
    ],
  },
  {
    slug: 'media',
    icons: [
      { filename: 'image', alternatives: ['fill'], keywords: ['photo', 'picture', 'graphic'] },
      { filename: 'image-broken', alternatives: ['fill'], keywords: ['image', 'broken', 'missing', 'error', 'photo'] },
      { filename: 'images', alternatives: ['fill'], keywords: ['photos', 'gallery', 'pictures'] },
      { filename: 'landscape', alternatives: ['fill'], keywords: ['landscape', 'photo', 'scenery', 'nature', 'image'] },
      { filename: 'camera', alternatives: ['fill'], keywords: ['photo', 'capture', 'picture'] },
      { filename: 'videocam', alternatives: ['fill'], keywords: ['video', 'record', 'film'] },
      { filename: 'movie', alternatives: ['fill'], keywords: ['movie', 'film', 'cinema', 'video'] },
      { filename: 'split-scene', alternatives: ['fill'], keywords: ['split', 'scene', 'compare', 'before after'] },
      { filename: 'volume-mute', alternatives: ['fill'], keywords: ['sound', 'silent', 'off', 'speaker'] },
      { filename: 'volume-down', alternatives: ['fill'], keywords: ['sound', 'audio', 'quieter', 'speaker'] },
      { filename: 'volume-up', alternatives: ['fill'], keywords: ['sound', 'audio', 'louder', 'speaker'] },
      { filename: 'volume-off', alternatives: ['fill'], keywords: ['mute', 'silent', 'sound', 'speaker'] },
      { filename: 'play-circle', alternatives: ['fill'], keywords: ['video', 'media', 'start'] },
      { filename: 'play-box', alternatives: ['fill'], keywords: ['video', 'media', 'start'] },
      { filename: 'play', alternatives: ['fill'], keywords: ['start', 'video', 'media'] },
      { filename: 'pause', alternatives: ['fill'], keywords: ['media', 'player', 'controls', 'stop'] },
      { filename: 'stop', alternatives: ['fill'], keywords: ['media', 'player', 'controls', 'square', 'end'] },
      { filename: 'skip-prev', alternatives: ['fill'], keywords: ['previous', 'back', 'rewind', 'media', 'player', 'track', 'controls'] },
      { filename: 'skip-next', alternatives: ['fill'], keywords: ['next', 'forward', 'media', 'player', 'track', 'controls'] },
      { filename: 'headphones', alternatives: ['fill'], keywords: ['audio', 'listen', 'sound', 'music'] },
      { filename: 'music', alternatives: [], keywords: ['note', 'audio', 'song', 'sound'] },
      { filename: 'music-note', alternatives: [], keywords: ['music', 'note', 'audio', 'song'] },
    ],
  },
  {
    slug: 'files',
    icons: [
      { filename: 'folder', alternatives: ['fill'], keywords: ['directory', 'files'] },
      { filename: 'folder-open', alternatives: ['fill'], keywords: ['directory', 'files', 'open'] },
      { filename: 'folder-copy', alternatives: ['fill'], keywords: ['folder', 'copy', 'duplicate', 'files'] },
      { filename: 'folder-zip', alternatives: ['fill'], keywords: ['archive', 'compressed', 'zip'] },
      { filename: 'file-audio', alternatives: ['fill'], keywords: ['sound', 'music', 'mp3'] },
      { filename: 'file-video', alternatives: ['fill'], keywords: ['movie', 'film', 'mp4'] },
      { filename: 'file-attachment', alternatives: ['fill'], keywords: ['attachment', 'attach', 'clip', 'upload', 'document'] },
      { filename: 'file-pdf', alternatives: ['fill'], keywords: ['pdf', 'document', 'acrobat', 'export'] },
      { filename: 'database', alternatives: ['fill'], keywords: ['storage', 'server', 'data', 'sql'] },
      { filename: 'cloud', alternatives: ['fill'], keywords: ['storage', 'upload', 'server'] },
      { filename: 'backup', alternatives: ['fill'], keywords: ['restore', 'cloud', 'save', 'copy'] },
      { filename: 'archive', alternatives: ['fill'], keywords: ['archive', 'storage', 'box', 'save'] },
    ],
  },
  {
    slug: 'analytics',
    icons: [
      { filename: 'chart-pie', alternatives: ['fill'], keywords: ['graph', 'statistics', 'analytics'] },
      { filename: 'chart-area', alternatives: ['fill'], keywords: ['chart', 'area', 'graph', 'analytics'] },
      { filename: 'chart-bubble', alternatives: ['fill'], keywords: ['chart', 'bubble', 'graph', 'analytics'] },
      { filename: 'chart-bar', alternatives: [], keywords: ['graph', 'statistics', 'analytics', 'columns'] },
      { filename: 'chart-bar-alt', alternatives: [], keywords: ['graph', 'statistics', 'analytics', 'columns', 'bars'] },
      { filename: 'chart-monitoring', alternatives: [], keywords: ['monitoring', 'line', 'analytics', 'graph', 'trend', 'activity'] },
      { filename: 'chart-line', alternatives: [], keywords: ['chart', 'line', 'graph', 'trend'] },
      { filename: 'chart-line-alt', alternatives: [], keywords: ['chart', 'line', 'graph', 'trend', 'alt'] },
      { filename: 'chart-data', alternatives: ['fill'], keywords: ['graph', 'analytics', 'statistics', 'report', 'insights'] },
      { filename: 'trending-up', alternatives: [], keywords: ['growth', 'increase', 'arrow', 'analytics', 'rise', 'up'] },
      { filename: 'trending-down', alternatives: [], keywords: ['decrease', 'decline', 'arrow', 'analytics', 'fall', 'down'] },
      { filename: 'timeline', alternatives: [], keywords: ['process', 'steps', 'history', 'milestones', 'sequence', 'progress'] },
      { filename: 'dashboard', alternatives: ['fill'], keywords: ['gauge', 'overview', 'panel', 'speedometer'] },
      { filename: 'dashboard-alt', alternatives: ['fill'], keywords: ['overview', 'panel', 'widgets'] },
      { filename: 'data-table', alternatives: ['fill'], keywords: ['grid', 'rows', 'spreadsheet'] },
      { filename: 'dns', alternatives: ['fill'], keywords: ['dns', 'domain', 'network', 'server'] },
      { filename: 'table', alternatives: ['fill'], keywords: ['grid', 'rows', 'columns', 'spreadsheet'] },
      { filename: 'analytics', alternatives: ['fill'], keywords: ['analytics', 'statistics', 'metrics', 'insights'] },
      { filename: 'list-box', alternatives: ['fill'], keywords: ['list', 'panel', 'items'] },
    ],
  },
  {
    slug: 'layout',
    icons: [
      {
        filename: 'content-grid',
        alternatives: ['fill'],
        keywords: ['content', 'grid', 'catalog', 'library', 'layout', 'panels', 'browse', 'view'],
      },
      { filename: 'widgets', alternatives: ['fill'], keywords: ['widget', 'blocks', 'layout', 'components'] },
      { filename: 'category', alternatives: ['fill'], keywords: ['category', 'folder', 'taxonomy', 'group'] },
      { filename: 'interests', alternatives: ['fill'], keywords: ['interests', 'hobbies', 'heart', 'topics'] },
      { filename: 'grid', alternatives: ['fill'], keywords: ['layout', 'tiles', 'gallery'] },
      { filename: 'grid-3x3', alternatives: [], keywords: ['layout', 'tiles', 'gallery'] },
      { filename: 'grid-4x4', alternatives: [], keywords: ['layout', 'tiles', 'gallery'] },
      { filename: 'view-column', alternatives: ['fill'], keywords: ['layout', 'columns'] },
      { filename: 'view-comfy', alternatives: ['fill'], keywords: ['layout', 'grid', 'tiles'] },
      { filename: 'view-list', alternatives: ['fill'], keywords: ['layout', 'rows', 'list'] },
      { filename: 'view-grid', alternatives: ['fill'], keywords: ['layout', 'tiles', 'gallery'] },
      { filename: 'view-grid-alt', alternatives: ['fill'], keywords: ['layout', 'tiles'] },
      { filename: 'cards', alternatives: ['fill'], keywords: ['cards', 'layout', 'grid', 'blocks'] },
      { filename: 'two-pager', alternatives: ['fill'], keywords: ['document', 'pages', 'spread', 'brochure'] },
      { filename: 'layers', alternatives: ['fill'], keywords: ['stack', 'layout', 'overlay', 'levels', 'z-index'] },
      { filename: 'stacks', alternatives: ['fill'], keywords: ['stack', 'layers', 'collection'] },
      { filename: 'aspect-ratio', alternatives: ['fill'], keywords: ['aspect', 'ratio', 'dimensions', 'layout'] },
      { filename: 'toolbar', alternatives: ['fill'], keywords: ['toolbar', 'bar', 'controls', 'layout'] },
      { filename: 'wp-block', alternatives: ['fill'], keywords: ['wordpress', 'gutenberg', 'brick'] },
      { filename: 'stories', alternatives: ['fill'], keywords: ['story', 'reels', 'vertical', 'social'] },
      { filename: 'carousel', alternatives: ['fill'], keywords: ['slider', 'gallery', 'slideshow'] },
      { filename: 'call-to-action', alternatives: ['fill'], keywords: ['cta', 'call to action', 'button', 'promote'] },
      { filename: 'brick', alternatives: ['fill'], keywords: ['block', 'gutenberg', 'layout', 'section'] },
    ],
  },
  {
    slug: 'commerce',
    icons: [
      { filename: 'shopping-cart', alternatives: ['fill'], keywords: ['cart', 'buy', 'ecommerce', 'checkout'] },
      { filename: 'shopping-cart-off', alternatives: ['fill'], keywords: ['cart', 'disabled', 'removed', 'empty', 'unavailable', 'no'] },
      { filename: 'shopping-cart-add', alternatives: [], keywords: ['cart', 'buy', 'plus'] },
      { filename: 'shopping-cart-remove', alternatives: [], keywords: ['cart', 'minus', 'remove'] },
      { filename: 'shopping-basket', alternatives: ['fill'], keywords: ['basket', 'buy', 'cart'] },
      { filename: 'shopping-bag', alternatives: ['fill'], keywords: ['shopping', 'bag', 'retail', 'buy'] },
      { filename: 'package', alternatives: ['fill'], keywords: ['box', 'parcel', 'delivery', 'shipping', 'order'] },
      { filename: 'sell-tag', alternatives: ['fill'], keywords: ['sell', 'tag', 'price', 'offer', 'sale'] },
      { filename: 'contactless', alternatives: ['fill'], keywords: ['payment', 'tap', 'nfc', 'wireless', 'pay'] },
      { filename: 'credit-card', alternatives: ['fill'], keywords: ['payment', 'card', 'pay'] },
      { filename: 'payment-card', alternatives: ['fill'], keywords: ['payment', 'card', 'credit card', 'debit', 'pay'] },
      { filename: 'payments', alternatives: ['fill'], keywords: ['money', 'pay', 'cash', 'finance'] },
      { filename: 'finance-chip', alternatives: ['fill'], keywords: ['finance', 'chip', 'payment', 'money'] },
      { filename: 'atm', alternatives: ['fill'], keywords: ['atm', 'cash', 'bank', 'withdraw'] },
      { filename: 'receipt', alternatives: ['fill'], keywords: ['receipt', 'invoice', 'bill', 'purchase', 'order'] },
      { filename: 'checkbook', alternatives: ['fill'], keywords: ['checkbook', 'check', 'cheque', 'payment', 'finance', 'bank'] },
      { filename: 'wallet', alternatives: ['fill'], keywords: ['wallet', 'money', 'payment', 'finance', 'purse'] },
      { filename: 'wallet-alt', alternatives: ['fill'], keywords: ['wallet', 'money', 'payment', 'alt'] },
      { filename: 'money-bag', alternatives: ['fill'], keywords: ['money', 'bag', 'cash', 'savings'] },
      { filename: 'savings', alternatives: ['fill'], keywords: ['savings', 'money', 'bank', 'piggy'] },
      { filename: 'bank', alternatives: ['fill'], keywords: ['bank', 'finance', 'building', 'money', 'institution'] },
      { filename: 'universal-currency', alternatives: ['fill'], keywords: ['currency', 'money', 'exchange', 'global'] },
      { filename: 'dollar-circle', alternatives: ['fill'], keywords: ['dollar', 'money', 'currency', 'price'] },
      { filename: 'currency-exchange', alternatives: [], keywords: ['money', 'exchange', 'convert', 'forex', 'rates'] },
      { filename: 'currency-dollar', alternatives: [], keywords: ['money', 'usd', 'price'] },
      { filename: 'currency-euro', alternatives: [], keywords: ['money', 'eur', 'price'] },
      { filename: 'currency-pound', alternatives: [], keywords: ['money', 'gbp', 'price'] },
      { filename: 'currency-yen', alternatives: [], keywords: ['money', 'jpy', 'price'] },
      { filename: 'currency-franc', alternatives: [], keywords: ['money', 'chf', 'franc', 'swiss', 'price'] },
      { filename: 'currency-lira', alternatives: [], keywords: ['money', 'try', 'lira', 'turkish', 'price'] },
      { filename: 'currency-ruble', alternatives: [], keywords: ['money', 'rub', 'ruble', 'russian', 'price'] },
      { filename: 'currency-rupee', alternatives: [], keywords: ['money', 'inr', 'rupee', 'indian', 'price'] },
      { filename: 'currency-yuan', alternatives: [], keywords: ['money', 'cny', 'yuan', 'renminbi', 'chinese', 'price'] },
      { filename: 'currency-bitcoin', alternatives: [], keywords: ['money', 'btc', 'bitcoin', 'crypto', 'cryptocurrency'] },
      { filename: 'copyright', alternatives: ['fill'], keywords: ['copyright', 'legal', 'ip', 'symbol'] },
      { filename: 'handshake', alternatives: ['fill'], keywords: ['handshake', 'deal', 'partnership', 'agreement'] },
      { filename: 'contract', alternatives: ['fill'], keywords: ['contract', 'document', 'agreement', 'legal'] },
      { filename: 'contract-sign', alternatives: ['fill'], keywords: ['contract', 'sign', 'signature', 'agreement'] },
      { filename: 'gavel', alternatives: [], keywords: ['gavel', 'law', 'court', 'legal', 'auction'] },
      { filename: 'balance', alternatives: [], keywords: ['balance', 'scale', 'justice', 'law', 'weight'] },
      { filename: 'license', alternatives: ['fill'], keywords: ['license', 'certificate', 'permit', 'badge'] },
      { filename: 'unlicense', alternatives: ['fill'], keywords: ['unlicense', 'unlicensed', 'no license', 'blocked', 'legal', 'permit'] },
      { filename: 'visa', alternatives: [], keywords: ['payment', 'card', 'credit card', 'brand'] },
      { filename: 'mastercard', alternatives: [], keywords: ['payment', 'card', 'credit card', 'brand'] },
      { filename: 'paypal', alternatives: [], keywords: ['payment', 'pay', 'wallet', 'brand'] },
      { filename: 'applepay', alternatives: [], keywords: ['payment', 'apple', 'pay', 'wallet', 'brand'] },
      { filename: 'googlepay', alternatives: [], keywords: ['payment', 'google', 'pay', 'wallet', 'brand'] },
      { filename: 'klarna', alternatives: [], keywords: ['payment', 'pay', 'bnpl', 'buy now pay later', 'brand'] },
    ],
  },
  {
    slug: 'people',
    icons: [
      { filename: 'account', alternatives: ['fill'], keywords: ['user', 'profile', 'person'] },
      { filename: 'account-box', alternatives: ['fill'], keywords: ['account', 'user', 'profile', 'box'] },
      { filename: 'person', alternatives: ['fill'], keywords: ['user', 'profile', 'account'] },
      { filename: 'group', alternatives: ['fill'], keywords: ['team', 'people', 'users'] },
      { filename: 'face', alternatives: ['fill'], keywords: ['user', 'avatar', 'profile'] },
      { filename: 'face-alt', alternatives: ['fill'], keywords: ['face', 'avatar', 'profile', 'user', 'alt'] },
      { filename: 'face-female', alternatives: ['fill'], keywords: ['face', 'female', 'woman', 'avatar', 'profile', 'user'] },
      { filename: 'id-card', alternatives: ['fill'], keywords: ['identity', 'badge', 'profile'] },
      { filename: 'badge', alternatives: ['fill'], keywords: ['badge', 'id', 'name tag', 'employee', 'lanyard', 'credential'] },
      { filename: 'passport', alternatives: ['fill'], keywords: ['passport', 'travel', 'identity', 'document'] },
      { filename: 'gender-male', alternatives: [], keywords: ['man', 'sex', 'symbol'] },
      { filename: 'gender-female', alternatives: [], keywords: ['woman', 'sex', 'symbol'] },
      { filename: 'man', alternatives: [], keywords: ['male', 'person', 'user'] },
      { filename: 'woman', alternatives: [], keywords: ['female', 'person', 'user'] },
      { filename: 'pregnant-woman', alternatives: [], keywords: ['pregnant', 'woman', 'maternity', 'mother', 'expecting'] },
      { filename: 'accessibility', alternatives: [], keywords: ['a11y', 'wheelchair', 'disability', 'access'] },
      { filename: 'accessibility-alt', alternatives: [], keywords: ['accessibility', 'a11y', 'universal', 'access'] },
      { filename: 'sign-language', alternatives: ['fill'], keywords: ['sign language', 'accessibility', 'hands', 'deaf'] },
      { filename: 'suitcase', alternatives: ['fill'], keywords: ['suitcase', 'travel', 'luggage', 'trip'] },
      { filename: 'work', alternatives: ['fill'], keywords: ['work', 'briefcase', 'job', 'business'] },
    ],
  },
  {
    slug: 'places',
    icons: [
      { filename: 'map', alternatives: ['fill'], keywords: ['location', 'navigation', 'directions'] },
      { filename: 'map-search', alternatives: ['fill'], keywords: ['map', 'search', 'location', 'find'] },
      { filename: 'location', alternatives: ['fill'], keywords: ['pin', 'map', 'marker', 'place', 'gps'] },
      { filename: 'pin', alternatives: ['fill'], keywords: ['pin', 'location', 'marker', 'place'] },
      { filename: 'pin-off', alternatives: ['fill'], keywords: ['pin', 'remove', 'unpin', 'location'] },
      { filename: 'pin-drop', alternatives: ['fill'], keywords: ['location', 'marker', 'map', 'place'] },
      { filename: 'pin-circle', alternatives: ['fill'], keywords: ['pin', 'location', 'circle', 'marker'] },
      { filename: 'location-add', alternatives: ['fill'], keywords: ['add', 'location', 'pin', 'place', 'map'] },
      { filename: 'location-heart', alternatives: ['fill'], keywords: ['favorite', 'location', 'place', 'saved'] },
      { filename: 'compass', alternatives: ['fill'], keywords: ['navigation', 'direction', 'explore'] },
      { filename: 'navigation', alternatives: ['fill'], keywords: ['direction', 'gps', 'near me', 'explore', 'arrow', 'maps'] },
      { filename: 'navigation-alt-me', alternatives: ['fill'], keywords: ['my location', 'gps', 'me', 'position'] },
      { filename: 'nearby', alternatives: ['fill'], keywords: ['near me', 'local', 'around', 'location'] },
      { filename: 'recenter', alternatives: [], keywords: ['recenter', 'map', 'center', 'refocus', 'location'] },
      { filename: 'signpost', alternatives: ['fill'], keywords: ['direction', 'guide', 'wayfinding', 'route'] },
      { filename: 'globe', alternatives: [], keywords: ['world', 'earth', 'international', 'web'] },
      { filename: 'globe-america', alternatives: [], keywords: ['globe', 'america', 'world', 'international'] },
      { filename: 'globe-asia', alternatives: [], keywords: ['globe', 'asia', 'world', 'international'] },
      { filename: 'walk', alternatives: [], keywords: ['pedestrian', 'walking', 'steps', 'directions'] },
      { filename: 'footprint', alternatives: ['fill'], keywords: ['footprint', 'track', 'trail', 'walk', 'steps'] },
      { filename: 'bicycle', alternatives: [], keywords: ['bike', 'cycle', 'transport', 'ride'] },
      { filename: 'motorcycle', alternatives: ['fill'], keywords: ['motorcycle', 'bike', 'transport', 'ride'] },
      { filename: 'car', alternatives: ['fill'], keywords: ['vehicle', 'drive', 'transport', 'auto'] },
      { filename: 'parking', alternatives: [], keywords: ['parking', 'car', 'lot', 'park', 'p'] },
      { filename: 'traffic', alternatives: ['fill'], keywords: ['traffic', 'lights', 'signal', 'road', 'transport'] },
      { filename: 'train', alternatives: ['fill'], keywords: ['transport', 'rail', 'metro', 'subway', 'travel'] },
      { filename: 'ship', alternatives: ['fill'], keywords: ['boat', 'transport', 'cruise', 'sea', 'ferry', 'travel'] },
      { filename: 'sailing', alternatives: ['fill'], keywords: ['sailing', 'sailboat', 'boat', 'sea', 'sport', 'travel'] },
      { filename: 'anchor', alternatives: [], keywords: ['anchor', 'harbor', 'maritime', 'port'] },
      { filename: 'plane', alternatives: [], keywords: ['airplane', 'flight', 'travel', 'fly', 'airport'] },
      { filename: 'hotel', alternatives: ['fill'], keywords: ['hotel', 'lodging', 'accommodation', 'bed', 'stay', 'travel'] },
    ],
  },
  {
    slug: 'devices',
    icons: [
      { filename: 'devices', alternatives: ['fill'], keywords: ['devices', 'laptop', 'phone', 'mobile', 'computer', 'screen'] },
      { filename: 'laptop', alternatives: ['fill'], keywords: ['computer', 'notebook', 'device'] },
      { filename: 'laptop-alt', alternatives: ['fill'], keywords: ['computer', 'notebook'] },
      { filename: 'monitor', alternatives: ['fill'], keywords: ['monitor', 'screen', 'display', 'desktop'] },
      { filename: 'tv', alternatives: ['fill'], keywords: ['television', 'screen', 'monitor', 'display'] },
      { filename: 'mobile', alternatives: ['fill'], keywords: ['phone', 'smartphone', 'device'] },
      { filename: 'mobile-alt', alternatives: ['fill'], keywords: ['phone', 'smartphone'] },
      { filename: 'mobile-rotate', alternatives: ['fill'], keywords: ['mobile', 'rotate', 'orientation', 'phone'] },
      { filename: 'battery-full', alternatives: [], keywords: ['battery', 'full', 'charge', 'power', 'energy'] },
      { filename: 'battery-half', alternatives: [], keywords: ['battery', 'half', 'charge', 'power', 'energy'] },
      { filename: 'battery-low', alternatives: [], keywords: ['battery', 'low', 'empty', 'charge', 'power', 'energy'] },
      { filename: 'radio', alternatives: ['fill'], keywords: ['radio', 'audio', 'broadcast', 'fm', 'am', 'music'] },
      { filename: 'headset', alternatives: ['fill'], keywords: ['headset', 'audio', 'call', 'support'] },
      { filename: 'head-mounted-device', alternatives: ['fill'], keywords: ['vr', 'headset', 'ar', 'wearable'] },
      { filename: 'power', alternatives: ['fill'], keywords: ['power', 'on', 'energy', 'electricity', 'plug'] },
      { filename: 'power-unplugged', alternatives: ['fill'], keywords: ['power', 'off', 'unplugged', 'disconnect', 'energy', 'plug'] },
      { filename: 'power-off', alternatives: [], keywords: ['shutdown', 'standby', 'on', 'off'] },
      { filename: 'power-off-circle', alternatives: ['fill'], keywords: ['power', 'off', 'shutdown', 'circle'] },
      { filename: 'keyboard', alternatives: ['fill'], keywords: ['keyboard', 'type', 'input', 'keys'] },
      { filename: 'keyboard-capslock', alternatives: ['fill'], keywords: ['caps lock', 'keyboard', 'uppercase', 'keys'] },
      { filename: 'mouse', alternatives: ['fill'], keywords: ['click', 'cursor', 'device'] },
      { filename: 'pointer', alternatives: ['fill'], keywords: ['cursor', 'click', 'select', 'arrow', 'mouse'] },
      { filename: 'barcode', alternatives: [], keywords: ['scan', 'product', 'code'] },
      { filename: 'barcode-scan', alternatives: [], keywords: ['scan', 'product', 'code'] },
      { filename: 'qr-code', alternatives: [], keywords: ['qr', 'code', 'scan', 'barcode', 'link'] },
      { filename: 'qr-code-alt', alternatives: [], keywords: ['qr', 'code', 'scan', 'barcode'] },
      { filename: 'qr-code-scan', alternatives: [], keywords: ['qr', 'code', 'scan', 'camera', 'barcode'] },
      { filename: 'trackpad-input', alternatives: ['fill'], keywords: ['trackpad', 'touchpad', 'input', 'gesture'] },
      { filename: 'wifi', alternatives: [], keywords: ['wifi', 'wireless', 'network', 'internet'] },
      { filename: 'videogame', alternatives: ['fill'], keywords: ['videogame', 'gaming', 'controller', 'play'] },
      { filename: 'joystick', alternatives: ['fill'], keywords: ['joystick', 'gaming', 'controller', 'game'] },
    ],
  },
  {
    slug: 'security',
    icons: [
      { filename: 'lock', alternatives: ['fill'], keywords: ['secure', 'locked', 'private', 'password'] },
      { filename: 'lock-open', alternatives: ['fill'], keywords: ['unlocked', 'open', 'access'] },
      { filename: 'key', alternatives: ['fill'], keywords: ['password', 'access', 'login', 'unlock'] },
      { filename: 'password', alternatives: [], keywords: ['password', 'lock', 'secure', 'login'] },
      { filename: 'fingerprint', alternatives: [], keywords: ['fingerprint', 'biometric', 'auth', 'identity'] },
      { filename: 'login', alternatives: [], keywords: ['sign in', 'enter', 'access'] },
      { filename: 'logout', alternatives: [], keywords: ['sign out', 'exit', 'leave'] },
      { filename: 'cookie', alternatives: ['fill'], keywords: ['consent', 'privacy', 'gdpr'] },
      { filename: 'cookie-off', alternatives: ['fill'], keywords: ['cookie', 'off', 'privacy', 'consent', 'block'] },
      { filename: 'shield', alternatives: ['fill'], keywords: ['security', 'protection', 'guard'] },
      { filename: 'shield-check', alternatives: ['fill'], keywords: ['security', 'verified', 'protected', 'safe'] },
      { filename: 'shield-lock', alternatives: ['fill'], keywords: ['security', 'protected', 'private'] },
      { filename: 'shield-security', alternatives: [], keywords: ['protection', 'guard', 'safe'] },
      { filename: 'shield-info', alternatives: ['fill'], keywords: ['shield', 'info', 'security', 'protection'] },
      { filename: 'shield-star', alternatives: ['fill'], keywords: ['security', 'protection', 'badge', 'star', 'shield'] },
      { filename: 'verified', alternatives: ['fill'], keywords: ['check', 'badge', 'trusted', 'approved'] },
      { filename: 'cctv', alternatives: ['fill'], keywords: ['surveillance', 'camera', 'security', 'monitor', 'cctv'] },
      { filename: 'siren', alternatives: ['fill'], keywords: ['emergency', 'alert', 'warning', 'alarm', 'siren'] },
      { filename: 'emergency', alternatives: ['fill'], keywords: ['emergency', 'sos', 'crisis', 'help', 'alert'] },
    ],
  },
  {
    slug: 'controls',
    icons: [
      { filename: 'settings', alternatives: ['fill'], keywords: ['gear', 'cog', 'preferences', 'options'] },
      { filename: 'tune', alternatives: [], keywords: ['sliders', 'adjust', 'options'] },
      { filename: 'tune-alt', alternatives: [], keywords: ['sliders', 'adjust', 'options', 'vertical', 'tune'] },
      { filename: 'build', alternatives: ['fill'], keywords: ['build', 'wrench', 'tools', 'construct', 'configure'] },
      { filename: 'manufacturing', alternatives: ['fill'], keywords: ['manufacturing', 'production', 'industrial', 'factory', 'assembly'] },
      { filename: 'sort', alternatives: [], keywords: ['order', 'arrange', 'filter'] },
      { filename: 'sort-by-alpha', alternatives: [], keywords: ['order', 'alphabetical', 'az'] },
      { filename: 'filter', alternatives: [], keywords: ['funnel', 'sort', 'refine'] },
      { filename: 'filter-off', alternatives: [], keywords: ['funnel', 'clear', 'reset'] },
      { filename: 'filter-alt', alternatives: ['fill'], keywords: ['funnel', 'sort', 'refine'] },
      { filename: 'filter-alt-off', alternatives: ['fill'], keywords: ['funnel', 'clear', 'reset'] },
      { filename: 'dropdown', alternatives: ['fill'], keywords: ['caret', 'down', 'menu', 'select'] },
      { filename: 'toggle-off', alternatives: ['fill'], keywords: ['switch', 'off', 'disabled'] },
      { filename: 'toggle-on', alternatives: ['fill'], keywords: ['switch', 'on', 'enabled'] },
      { filename: 'checkbox', alternatives: [], keywords: ['check', 'box', 'unchecked', 'form'] },
      { filename: 'checkbox-checked', alternatives: ['fill'], keywords: ['check', 'form', 'selected'] },
      { filename: 'checkbox-indeterminate', alternatives: ['fill'], keywords: ['check', 'partial', 'form'] },
      { filename: 'radio-button', alternatives: [], keywords: ['option', 'form', 'circle'] },
      { filename: 'radio-button-checked', alternatives: [], keywords: ['option', 'form', 'selected'] },
      { filename: 'radio-button-partial', alternatives: [], keywords: ['option', 'form', 'partial'] },
      { filename: 'visibility', alternatives: ['fill'], keywords: ['eye', 'show', 'view', 'visible'] },
      { filename: 'visibility-off', alternatives: ['fill'], keywords: ['eye', 'hide', 'hidden', 'invisible', 'private', 'password'] },
      { filename: 'mode-light', alternatives: ['fill'], keywords: ['day', 'theme', 'sun', 'brightness'] },
      { filename: 'mode-dark', alternatives: ['fill'], keywords: ['night', 'theme', 'moon'] },
    ],
  },
  {
    slug: 'status',
    icons: [
      { filename: 'info', alternatives: ['fill'], keywords: ['information', 'help', 'details', 'about'] },
      { filename: 'info-alt', alternatives: [], keywords: ['information', 'help', 'details', 'alt'] },
      { filename: 'help', alternatives: ['fill'], keywords: ['question', 'support', 'faq'] },
      { filename: 'warning', alternatives: ['fill'], keywords: ['alert', 'caution', 'attention', 'error'] },
      { filename: 'error', alternatives: ['fill'], keywords: ['alert', 'exclamation', 'danger', 'problem', 'fail', 'warning'] },
      { filename: 'notifications', alternatives: ['fill'], keywords: ['bell', 'alert', 'alarm'] },
      { filename: 'notification-unread', alternatives: ['fill'], keywords: ['notification', 'unread', 'badge', 'alert'] },
      { filename: 'notifications-circle', alternatives: ['fill'], keywords: ['notification', 'bell', 'alert', 'circle'] },
      { filename: 'alarm', alternatives: ['fill'], keywords: ['alarm', 'alert', 'clock', 'wake', 'timer'] },
      { filename: 'timer', alternatives: ['fill'], keywords: ['timer', 'countdown', 'stopwatch', 'time'] },
      { filename: 'clock', alternatives: ['fill'], keywords: ['time', 'schedule', 'hour'] },
      { filename: 'clock-alt', alternatives: ['fill'], keywords: ['time', 'schedule', 'clock', 'alt'] },
      { filename: 'watch', alternatives: ['fill'], keywords: ['watch', 'time', 'wristwatch', 'schedule', 'wearable'] },
      { filename: 'watch-alt', alternatives: ['fill'], keywords: ['watch', 'time', 'wristwatch', 'schedule', 'wearable', 'alt'] },
      { filename: 'history', alternatives: [], keywords: ['history', 'past', 'time', 'archive', 'recent'] },
      { filename: 'hourglass', alternatives: ['fill'], keywords: ['time', 'wait', 'loading', 'timer'] },
      { filename: 'calendar', alternatives: ['fill'], keywords: ['date', 'schedule', 'event', 'day', 'blank'] },
      { filename: 'calendar-month', alternatives: ['fill'], keywords: ['date', 'month', 'schedule', 'event'] },
      { filename: 'calendar-text', alternatives: ['fill'], keywords: ['date', 'event', 'schedule', 'agenda'] },
      { filename: 'speed-low', alternatives: ['fill'], keywords: ['speed', 'slow', 'performance', 'low'] },
      { filename: 'speed-high', alternatives: ['fill'], keywords: ['speed', 'fast', 'performance', 'high'] },
      { filename: 'label', alternatives: ['fill'], keywords: ['tag', 'badge', 'category'] },
    ],
  },
  {
    slug: 'weather',
    icons: [
      { filename: 'sunny', alternatives: ['fill'], keywords: ['sun', 'weather', 'clear', 'bright', 'sunny'] },
      { filename: 'partly-cloudy', alternatives: ['fill'], keywords: ['weather', 'cloud', 'sun', 'partly cloudy', 'forecast'] },
      { filename: 'mixed-weather', alternatives: ['fill'], keywords: ['weather', 'partly cloudy', 'forecast', 'cloud', 'sun'] },
      { filename: 'rain', alternatives: ['fill'], keywords: ['rain', 'weather', 'precipitation', 'storm', 'water'] },
      { filename: 'thunderstorm', alternatives: ['fill'], keywords: ['storm', 'lightning', 'weather', 'thunder', 'rain'] },
      { filename: 'snowy', alternatives: ['fill'], keywords: ['snow', 'snowy', 'weather', 'winter', 'cloud', 'cold'] },
      { filename: 'foggy', alternatives: ['fill'], keywords: ['fog', 'foggy', 'weather', 'mist'] },
      {
        filename: 'partly-cloudy-night',
        alternatives: ['fill'],
        keywords: ['weather', 'cloud', 'moon', 'night', 'partly cloudy', 'forecast'],
      },
      { filename: 'moon', alternatives: ['fill'], keywords: ['moon', 'night', 'dark', 'theme', 'sleep'] },
      { filename: 'moon-stars', alternatives: ['fill'], keywords: ['moon', 'stars', 'night', 'sky', 'sleep'] },
      { filename: 'wind', alternatives: [], keywords: ['wind', 'weather', 'breeze', 'air'] },
      { filename: 'heat', alternatives: ['fill'], keywords: ['hot', 'temperature', 'heat', 'weather', 'summer'] },
      { filename: 'snowflake', alternatives: [], keywords: ['snow', 'winter', 'weather', 'cold', 'flake'] },
      { filename: 'cold', alternatives: [], keywords: ['cold', 'temperature', 'freeze', 'weather', 'winter'] },
      { filename: 'thermometer', alternatives: ['fill'], keywords: ['thermometer', 'temperature', 'weather', 'heat'] },
      { filename: 'thermometer-alt', alternatives: [], keywords: ['thermometer', 'temperature', 'weather', 'alt'] },
    ],
  },
  {
    slug: 'food-drink',
    icons: [
      { filename: 'dining', alternatives: [], keywords: ['dining', 'restaurant', 'food', 'eat', 'meal'] },
      { filename: 'fork-knife', alternatives: [], keywords: ['fork', 'knife', 'dining', 'restaurant'] },
      { filename: 'fork-spoon', alternatives: [], keywords: ['fork', 'spoon', 'dining', 'restaurant', 'eat'] },
      { filename: 'chef-hat', alternatives: ['fill'], keywords: ['chef', 'cook', 'kitchen', 'restaurant', 'hat'] },
      { filename: 'menu-book', alternatives: ['fill'], keywords: ['menu', 'book', 'reading', 'restaurant'] },
      { filename: 'burger', alternatives: ['fill'], keywords: ['burger', 'food', 'fast food', 'hamburger', 'meal'] },
      { filename: 'fast-food', alternatives: ['fill'], keywords: ['fast food', 'meal', 'takeaway', 'restaurant'] },
      { filename: 'pizza', alternatives: ['fill'], keywords: ['pizza', 'food', 'slice', 'italian'] },
      { filename: 'bakery', alternatives: ['fill'], keywords: ['bakery', 'bread', 'pastry', 'food'] },
      { filename: 'cake', alternatives: ['fill'], keywords: ['cake', 'dessert', 'birthday', 'sweet'] },
      { filename: 'icecream', alternatives: ['fill'], keywords: ['ice cream', 'dessert', 'sweet', 'food'] },
      { filename: 'nutrition', alternatives: ['fill'], keywords: ['nutrition', 'food', 'diet', 'health', 'apple'] },
      { filename: 'coffee', alternatives: ['fill'], keywords: ['coffee', 'drink', 'cafe', 'cup', 'espresso'] },
      { filename: 'tea', alternatives: ['fill'], keywords: ['tea', 'drink', 'cup', 'hot', 'cafe'] },
      { filename: 'glass', alternatives: ['fill'], keywords: ['glass', 'drink', 'cup', 'beverage'] },
      { filename: 'water-full', alternatives: ['fill'], keywords: ['water', 'glass', 'drink', 'hydration', 'cup'] },
      { filename: 'water-bottle', alternatives: ['fill'], keywords: ['water', 'bottle', 'drink', 'hydration'] },
      { filename: 'beer', alternatives: ['fill'], keywords: ['beer', 'drink', 'alcohol', 'bar', 'pub'] },
      { filename: 'wine', alternatives: ['fill'], keywords: ['wine', 'drink', 'alcohol', 'glass', 'bar'] },
      { filename: 'liquor', alternatives: ['fill'], keywords: ['liquor', 'alcohol', 'bottle', 'drink', 'spirits'] },
      { filename: 'cocktail', alternatives: ['fill'], keywords: ['cocktail', 'drink', 'alcohol', 'glass', 'bar'] },
      { filename: 'no-drinks', alternatives: ['fill'], keywords: ['no drinks', 'alcohol free', 'dry', 'prohibited', 'bar'] },
    ],
  },
  {
    slug: 'sports-fitness',
    icons: [
      { filename: 'exercise', alternatives: ['fill'], keywords: ['exercise', 'fitness', 'workout', 'training', 'gym'] },
      { filename: 'fitness', alternatives: [], keywords: ['fitness', 'workout', 'gym', 'health'] },
      { filename: 'swimming', alternatives: [], keywords: ['swimming', 'pool', 'sport', 'water', 'swim'] },
      { filename: 'football', alternatives: [], keywords: ['football', 'soccer', 'sport', 'ball', 'game'] },
      { filename: 'basketball', alternatives: ['fill'], keywords: ['basketball', 'sport', 'ball', 'hoop'] },
      { filename: 'volleyball', alternatives: [], keywords: ['volleyball', 'sport', 'ball', 'net', 'game'] },
      { filename: 'baseball', alternatives: ['fill'], keywords: ['baseball', 'sport', 'bat', 'ball'] },
      { filename: 'american-football', alternatives: ['fill'], keywords: ['american football', 'nfl', 'sport', 'ball'] },
      { filename: 'tennis', alternatives: ['fill'], keywords: ['tennis', 'sport', 'ball', 'racket', 'court'] },
      { filename: 'hockey', alternatives: [], keywords: ['hockey', 'sport', 'ice', 'stick'] },
      { filename: 'cricket', alternatives: ['fill'], keywords: ['cricket', 'sport', 'bat', 'ball'] },
      { filename: 'golf', alternatives: ['fill'], keywords: ['golf', 'sport', 'club', 'course'] },
      { filename: 'stadium', alternatives: ['fill'], keywords: ['stadium', 'arena', 'sport', 'event', 'venue'] },
      { filename: 'motorsports', alternatives: ['fill'], keywords: ['motorsports', 'racing', 'car', 'speed', 'sport'] },
      { filename: 'esports', alternatives: ['fill'], keywords: ['esports', 'gaming', 'controller', 'competitive'] },
      { filename: 'whistle', alternatives: ['fill'], keywords: ['whistle', 'referee', 'sport', 'coach'] },
      { filename: 'leaderboard', alternatives: ['fill'], keywords: ['leaderboard', 'ranking', 'score', 'top', 'podium', 'chart'] },
      { filename: 'scoreboard', alternatives: ['fill'], keywords: ['scoreboard', 'score', 'sports', 'results'] },
      { filename: 'trophy', alternatives: ['fill'], keywords: ['award', 'win', 'prize', 'achievement', 'cup', 'winner'] },
      { filename: 'medal', alternatives: ['fill'], keywords: ['medal', 'award', 'prize', 'achievement', 'winner', 'sport'] },
      { filename: 'medals', alternatives: ['fill'], keywords: ['medals', 'award', 'prize', 'winner', 'podium', 'ranking', 'achievement'] },
      { filename: 'target', alternatives: [], keywords: ['target', 'goal', 'aim', 'bullseye', 'focus'] },
    ],
  },
  {
    slug: 'health-medical',
    icons: [
      { filename: 'health-cross', alternatives: ['fill'], keywords: ['health', 'medical', 'wellness', 'care', 'heart'] },
      { filename: 'shield-health', alternatives: ['fill'], keywords: ['shield', 'health', 'protection', 'medical'] },
      { filename: 'medical-services', alternatives: ['fill'], keywords: ['medical', 'health', 'hospital', 'services', 'care'] },
      { filename: 'healing', alternatives: ['fill'], keywords: ['healing', 'health', 'recovery', 'medical'] },
      { filename: 'cardiology', alternatives: ['fill'], keywords: ['cardiology', 'heart', 'medical', 'health'] },
      { filename: 'vital-signs', alternatives: [], keywords: ['vital signs', 'health', 'medical', 'monitor'] },
      { filename: 'medical-mask', alternatives: ['fill'], keywords: ['medical', 'mask', 'face', 'health', 'protection'] },
      { filename: 'medical-mask-alt', alternatives: ['fill'], keywords: ['medical', 'mask', 'health', 'protection', 'alt'] },
      { filename: 'pill', alternatives: ['fill'], keywords: ['pill', 'medicine', 'drug', 'pharmacy'] },
      { filename: 'fluid', alternatives: ['fill'], keywords: ['fluid', 'liquid', 'medical', 'iv'] },
      { filename: 'fluid-syringe', alternatives: ['fill'], keywords: ['syringe', 'injection', 'medical', 'vaccine'] },
      { filename: 'allergies', alternatives: ['fill'], keywords: ['allergies', 'medical', 'health', 'reaction'] },
      { filename: 'labs', alternatives: ['fill'], keywords: ['lab', 'science', 'experiment', 'test tube', 'research'] },
      { filename: 'science', alternatives: ['fill'], keywords: ['science', 'lab', 'research', 'flask'] },
      { filename: 'virus', alternatives: ['fill'], keywords: ['virus', 'infection', 'medical', 'health'] },
      { filename: 'dna', alternatives: [], keywords: ['dna', 'genetics', 'science', 'biology'] },
    ],
  },
  {
    slug: 'nature-lifestyle',
    icons: [
      { filename: 'forest', alternatives: ['fill'], keywords: ['forest', 'trees', 'nature', 'woods', 'park'] },
      { filename: 'pine-tree', alternatives: ['fill'], keywords: ['pine', 'tree', 'forest', 'nature', 'evergreen'] },
      { filename: 'nature', alternatives: ['fill'], keywords: ['nature', 'outdoors', 'landscape', 'environment'] },
      { filename: 'nature-people', alternatives: ['fill'], keywords: ['nature', 'people', 'outdoors', 'hiking', 'park'] },
      { filename: 'flower', alternatives: ['fill'], keywords: ['flower', 'nature', 'plant', 'garden'] },
      { filename: 'flower-alt', alternatives: ['fill'], keywords: ['flower', 'nature', 'plant', 'alt'] },
      { filename: 'water', alternatives: [], keywords: ['water', 'liquid', 'drop', 'nature', 'sea'] },
      { filename: 'drop', alternatives: ['fill'], keywords: ['drop', 'water', 'liquid', 'drip'] },
      { filename: 'recycling', alternatives: [], keywords: ['recycle', 'eco', 'environment', 'sustainability', 'green'] },
      { filename: 'pets', alternatives: [], keywords: ['paw', 'animal', 'dog', 'cat', 'pet'] },
      { filename: 'dog', alternatives: ['fill'], keywords: ['dog', 'pet', 'animal', 'puppy'] },
      { filename: 'pet-supplies', alternatives: ['fill'], keywords: ['pet', 'supplies', 'food', 'animal', 'bowl'] },
      { filename: 'owl', alternatives: ['fill'], keywords: ['owl', 'bird', 'animal', 'night'] },
      { filename: 'bird', alternatives: ['fill'], keywords: ['bird', 'animal', 'nature', 'wildlife'] },
      { filename: 'bug', alternatives: ['fill'], keywords: ['bug', 'insect', 'beetle', 'animal', 'nature'] },
      { filename: 'mountain', alternatives: ['fill'], keywords: ['mountain', 'hiking', 'nature', 'peak', 'outdoors'] },
      { filename: 'landscape-alt', alternatives: ['fill'], keywords: ['landscape', 'scenery', 'mountains', 'nature', 'outdoors'] },
      { filename: 'beach', alternatives: ['fill'], keywords: ['beach', 'sea', 'vacation', 'sand', 'coast'] },
      { filename: 'camping', alternatives: ['fill'], keywords: ['camp', 'tent', 'outdoors', 'nature', 'hiking'] },
    ],
  },
  {
    slug: 'misc',
    icons: [
      { filename: 'rocket', alternatives: ['fill'], keywords: ['launch', 'startup', 'fast', 'boost'] },
      { filename: 'rocket-launch', alternatives: ['fill'], keywords: ['launch', 'startup', 'boost', 'space'] },
      { filename: 'planet', alternatives: ['fill'], keywords: ['space', 'world', 'astronomy', 'orbit', 'saturn', 'galaxy'] },
      { filename: 'lightbulb', alternatives: ['fill'], keywords: ['idea', 'tip', 'hint', 'bright'] },
      { filename: 'wand-stars', alternatives: ['fill'], keywords: ['magic', 'wand', 'auto', 'enhance', 'sparkle', 'wizard'] },
      { filename: 'star-shine', alternatives: ['fill'], keywords: ['star', 'shine', 'sparkle', 'featured', 'favorite', 'quality'] },
      { filename: 'editor-choice', alternatives: ['fill'], keywords: ['editor', 'choice', 'recommended', 'featured', 'badge'] },
      { filename: 'style', alternatives: ['fill'], keywords: ['design', 'format', 'appearance', 'paint'] },
      { filename: 'sticker', alternatives: ['fill'], keywords: ['sticker', 'label', 'badge', 'emoji', 'decoration'] },
      { filename: 'diamond', alternatives: ['fill'], keywords: ['gem', 'premium', 'jewel', 'quality'] },
      { filename: 'crown', alternatives: ['fill'], keywords: ['king', 'queen', 'premium', 'royal', 'vip', 'winner', 'best'] },
      { filename: 'school', alternatives: ['fill'], keywords: ['school', 'education', 'university', 'learning'] },
      { filename: 'deployed', alternatives: ['fill'], keywords: ['deploy', 'release', 'launch', 'cloud'] },
      { filename: 'puzzle', alternatives: ['fill'], keywords: ['extension', 'plugin', 'addon', 'integration', 'piece'] },
      { filename: 'bolt', alternatives: ['fill'], keywords: ['flash', 'energy', 'power', 'fast', 'lightning'] },
      { filename: 'factory', alternatives: ['fill'], keywords: ['factory', 'industrial', 'plant', 'manufacturing', 'building'] },
      { filename: 'engineering', alternatives: ['fill'], keywords: ['engineering', 'engineer', 'hard hat', 'construction', 'technical'] },
      { filename: 'construction', alternatives: [], keywords: ['maintenance', 'work', 'build', 'tools'] },
      { filename: 'chess', alternatives: ['fill'], keywords: ['chess', 'game', 'strategy', 'board', 'piece'] },
      { filename: 'toys', alternatives: ['fill'], keywords: ['toys', 'toy', 'car', 'play', 'children', 'kids'] },
      { filename: 'ticket', alternatives: ['fill'], keywords: ['ticket', 'event', 'admission', 'pass'] },
      { filename: 'ticket-alt', alternatives: ['fill'], keywords: ['ticket', 'event', 'admission', 'pass', 'alt'] },
      { filename: 'castle', alternatives: ['fill'], keywords: ['castle', 'landmark', 'building', 'fort'] },
      { filename: 'shirt', alternatives: ['fill'], keywords: ['shirt', 'clothing', 'apparel', 'fashion', 'wear'] },
      { filename: 'eyeglasses', alternatives: [], keywords: ['glasses', 'vision', 'read', 'optical', 'eyewear'] },
      { filename: 'mask', alternatives: ['fill'], keywords: ['mask', 'disguise', 'carnival', 'theater', 'face'] },
      { filename: 'fire-extinguisher', alternatives: ['fill'], keywords: ['fire', 'extinguisher', 'safety', 'emergency'] },
      { filename: 'fire-hydrant', alternatives: ['fill'], keywords: ['fire', 'hydrant', 'emergency', 'water'] },
      { filename: 'bomb', alternatives: ['fill'], keywords: ['bomb', 'explosive', 'danger', 'blast'] },
      { filename: 'skull', alternatives: ['fill'], keywords: ['skull', 'danger', 'death', 'pirate', 'halloween'] },
      { filename: 'wc', alternatives: [], keywords: ['toilet', 'restroom', 'bathroom', 'wc', 'lavatory'] },
    ],
  },
  {
    slug: 'brands',
    icons: [
      { filename: 'wordpress', alternatives: [], keywords: ['blog', 'cms', 'wp', 'website'] },
      { filename: 'facebook', alternatives: [], keywords: ['social', 'meta', 'fb'] },
      { filename: 'instagram', alternatives: [], keywords: ['social', 'meta', 'ig', 'photos'] },
      { filename: 'x', alternatives: [], keywords: ['twitter', 'tweet', 'social'] },
      { filename: 'youtube', alternatives: [], keywords: ['video', 'streaming', 'google', 'social'] },
      { filename: 'linkedin', alternatives: [], keywords: ['social', 'jobs', 'network', 'professional', 'business', 'career'] },
      { filename: 'tiktok', alternatives: [], keywords: ['social', 'video', 'short'] },
      { filename: 'pinterest', alternatives: [], keywords: ['social', 'pin', 'board'] },
      { filename: 'threads', alternatives: [], keywords: ['social', 'meta', 'instagram'] },
      { filename: 'snapchat', alternatives: [], keywords: ['social', 'snap', 'ghost'] },
      { filename: 'reddit', alternatives: [], keywords: ['social', 'forum', 'community'] },
      { filename: 'tumblr', alternatives: [], keywords: ['social', 'blog'] },
      { filename: 'mastodon', alternatives: [], keywords: ['social', 'fediverse', 'toot'] },
      { filename: 'bluesky', alternatives: [], keywords: ['social', 'bsky', 'butterfly'] },
      { filename: 'xing', alternatives: [], keywords: ['social', 'jobs', 'network', 'professional', 'business'] },
      { filename: 'weibo', alternatives: [], keywords: ['social', 'china', 'microblog'] },
      { filename: 'medium', alternatives: [], keywords: ['blog', 'publishing', 'articles', 'writing'] },
      { filename: 'whatsapp', alternatives: [], keywords: ['messaging', 'chat', 'meta', 'message'] },
      { filename: 'telegram', alternatives: [], keywords: ['messaging', 'chat', 'message'] },
      { filename: 'messenger', alternatives: [], keywords: ['messaging', 'facebook', 'meta', 'chat', 'message'] },
      { filename: 'signal', alternatives: [], keywords: ['messaging', 'chat', 'private', 'message'] },
      { filename: 'imessage', alternatives: [], keywords: ['messaging', 'messages', 'apple', 'chat'] },
      { filename: 'wechat', alternatives: [], keywords: ['messaging', 'weixin', 'chat', 'china'] },
      { filename: 'line', alternatives: [], keywords: ['messaging', 'chat', 'japan'] },
      { filename: 'discord', alternatives: [], keywords: ['chat', 'gaming', 'community', 'voice'] },
      { filename: 'slack', alternatives: [], keywords: ['messaging', 'team', 'work', 'chat', 'collaboration'] },
      { filename: 'youtubeshorts', alternatives: [], keywords: ['video', 'youtube', 'shorts', 'short'] },
      { filename: 'vimeo', alternatives: [], keywords: ['video', 'streaming'] },
      { filename: 'twitch', alternatives: [], keywords: ['video', 'streaming', 'gaming', 'live'] },
      { filename: 'spotify', alternatives: [], keywords: ['music', 'audio', 'streaming'] },
      { filename: 'soundcloud', alternatives: [], keywords: ['music', 'audio', 'streaming'] },
      { filename: 'applemusic', alternatives: [], keywords: ['music', 'audio', 'streaming', 'apple'] },
      { filename: 'behance', alternatives: [], keywords: ['portfolio', 'design', 'creative', 'adobe'] },
      { filename: 'dribbble', alternatives: [], keywords: ['portfolio', 'design', 'creative', 'shots'] },
      { filename: 'github', alternatives: [], keywords: ['code', 'git', 'repository', 'developer', 'octocat'] },
      { filename: 'gitlab', alternatives: [], keywords: ['code', 'git', 'repository', 'developer'] },
      { filename: 'trello', alternatives: [], keywords: ['board', 'kanban', 'project', 'tasks', 'atlassian'] },
      { filename: 'patreon', alternatives: [], keywords: ['membership', 'support', 'creator', 'donate'] },
      { filename: 'yelp', alternatives: [], keywords: ['reviews', 'business', 'local', 'ratings'] },
      { filename: 'google', alternatives: [], keywords: ['search', 'brand', 'g'] },
      { filename: 'microsoft', alternatives: [], keywords: ['windows', 'office', 'tech'] },
      { filename: 'apple', alternatives: [], keywords: ['mac', 'ios', 'iphone', 'tech', 'logo'] },
    ],
  },
];

// Project/customer icons (assets/icons/theme/) surface at the top of the picker.
// The list is generated by scripts/build-icons.mjs into ./icons.generated.js.
export const iconCategories = themeIconCategory.icons.length ? [themeIconCategory, ...builtInCategories] : builtInCategories;

/** Flat list of every icon across all categories. */
export const allIcons = iconCategories.reduce((icons, category) => icons.concat(category.icons), []);

/** Whether an icon offers the given variant (e.g. 'fill'). */
export const hasVariant = (icon, variant) => !!icon && !!variant && icon.alternatives.indexOf(variant) !== -1;

/**
 * Resolve an icon to the file name for a variant. Falls back to the base
 * (outline) file name when the requested variant does not exist, so every
 * icon stays selectable regardless of the active variant.
 */
export const resolveIconName = (icon, variant) =>
  variant && variant !== 'outline' && hasVariant(icon, variant) ? `${icon.filename}-${variant}` : icon.filename;

/**
 * Match an icon against a lowercased search query.
 *
 * Searches the file name, the (localized) display name passed in, and the
 * static keywords.
 */
export const iconMatchesQuery = (icon, query, displayName = '') => {
  if (!query) {
    return true;
  }

  const haystack = [icon.filename, displayName].concat(icon.keywords).join(' ').toLowerCase();

  return haystack.indexOf(query) !== -1;
};

/**
 * Find the icon + variant for a stored value (e.g. `heart-fill`).
 * Returns null when the value does not match any catalog icon.
 */
export const findIconByValue = (value) => {
  if (!value) {
    return null;
  }

  for (const icon of allIcons) {
    if (icon.filename === value) {
      return { icon, variant: 'outline' };
    }

    for (const variant of icon.alternatives) {
      if (value === `${icon.filename}-${variant}`) {
        return { icon, variant };
      }
    }
  }

  return null;
};
