import { createRequire } from 'node:module';
import { readdirSync, existsSync, writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const require = createRequire(import.meta.url);
const { themeDir } = require('./config.cjs');

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');
const themeRoot = path.join(root, themeDir);

const configPath = path.join(themeRoot, 'config/icons.js');
const generatedJsPath = path.join(
  themeRoot,
  'src/js/editor/icons/icons.generated.js'
);
const cssOutPath = path.join(themeRoot, 'assets/css/icons.css');

// Physical folder under assets/ (class prefix stays "theme" via config.prefix).
const ICONS_DIR = 'icons-theme';

// "calendar-month" -> "Calendar month"
const humanize = (slug) =>
  slug.replace(/-/g, ' ').replace(/^\w/, (char) => char.toUpperCase());

async function loadConfig() {
  if (!existsSync(configPath)) {
    return {};
  }

  const module = await import(pathToFileURL(configPath).href);
  return module.themeIcons || {};
}

// Scan the folder for `<name>.svg` (+ optional `<name>-fill.svg`) and build the
// icon list, merged with the optional per-file metadata.
function collectIcons(folderAbs, classPrefix, meta) {
  if (!existsSync(folderAbs)) {
    return [];
  }

  const bases = new Set();
  const fills = new Set();

  for (const file of readdirSync(folderAbs)) {
    if (!file.endsWith('.svg')) {
      continue;
    }

    const name = file.replace(/\.svg$/, '');

    if (name.endsWith('-fill')) {
      fills.add(name.slice(0, -'-fill'.length));
    } else {
      bases.add(name);
    }
  }

  return [...bases].sort().map((base) => {
    const info = (meta && meta[base]) || {};

    return {
      base,
      class: `${classPrefix}-${base}`,
      filename: `${classPrefix}-${base}`,
      label: info.label || humanize(base),
      keywords: Array.isArray(info.keywords) ? info.keywords : [],
      hasFill: fills.has(base)
    };
  });
}

function renderJs(category, icons) {
  const items = icons.map((icon) => {
    const alternatives = icon.hasFill ? "['fill']" : '[]';
    return (
      `    { filename: ${JSON.stringify(icon.filename)}, ` +
      `label: ${JSON.stringify(icon.label)}, ` +
      `keywords: ${JSON.stringify(icon.keywords)}, ` +
      `alternatives: ${alternatives} }`
    );
  });

  const body = items.length ? `\n${items.join(',\n')}\n  ` : '';

  return `// GENERATED by scripts/build-icons.mjs -- do not edit by hand.
// Source: assets/${ICONS_DIR}/*.svg (+ config/icons.js)
export const themeIconCategory = {
  slug: ${JSON.stringify(category.slug)},
  label: ${JSON.stringify(category.label)},
  icons: [${body}]
};
`;
}

function renderCss(icons) {
  const lines = [
    '/* GENERATED by scripts/build-icons.mjs -- do not edit by hand. */',
    `/* Source: assets/${ICONS_DIR}/*.svg (+ config/icons.js) */`,
    ''
  ];

  for (const icon of icons) {
    lines.push(
      `.-icon-${icon.class} { --bl-icon: url('../${ICONS_DIR}/${icon.base}.svg'); }`
    );

    if (icon.hasFill) {
      lines.push(
        `.-icon-${icon.class}-fill { --bl-icon: url('../${ICONS_DIR}/${icon.base}-fill.svg'); }`
      );
    }
  }

  lines.push('');
  return lines.join('\n');
}

async function build() {
  const config = await loadConfig();
  const classPrefix = config.prefix || 'theme';
  const category = config.category || { slug: classPrefix, label: humanize(classPrefix) };
  const meta = config.meta || {};

  const folderAbs = path.join(themeRoot, 'assets', ICONS_DIR);
  const icons = collectIcons(folderAbs, classPrefix, meta);

  mkdirSync(path.dirname(cssOutPath), { recursive: true });
  writeFileSync(generatedJsPath, renderJs(category, icons));
  writeFileSync(cssOutPath, renderCss(icons));

  console.log(
    `\u2714 icons: generated ${icons.length} theme icon(s) from assets/${ICONS_DIR}/`
  );
}

await build();
