import { createRequire } from 'node:module';
import { readdirSync, existsSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const require = createRequire(import.meta.url);
const { themeDir } = require('./config.cjs');

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');
const themeRoot = path.join(root, themeDir);

const configPath = path.join(themeRoot, 'config/icons.js');
const generatedJsPath = path.join(
  themeRoot,
  'src/js/editor/icons/icons.generated.js'
);
const generatedScssPath = path.join(themeRoot, 'src/scss/icons/_icons-theme.scss');

// "calendar-month" -> "Calendar month"
const humanize = (slug) =>
  slug.replace(/-/g, ' ').replace(/^\w/, (char) => char.toUpperCase());

async function loadConfig() {
  if (!existsSync(configPath)) {
    return {};
  }

  const module = await import(pathToFileURL(configPath).href);
  return module.themeIcons || {};
}

// Scan the folder for `<name>.svg` (+ optional `<name>-fill.svg`) and build the
// icon list, merged with the optional per-file metadata.
function collectIcons(folderAbs, folder, meta) {
  if (!existsSync(folderAbs)) {
    return [];
  }

  const bases = new Set();
  const fills = new Set();

  for (const file of readdirSync(folderAbs)) {
    if (!file.endsWith('.svg')) {
      continue;
    }

    const name = file.replace(/\.svg$/, '');

    if (name.endsWith('-fill')) {
      fills.add(name.slice(0, -'-fill'.length));
    } else {
      bases.add(name);
    }
  }

  return [...bases].sort().map((base) => {
    const info = (meta && meta[base]) || {};

    return {
      base,
      class: `${folder}-${base}`,
      filename: `${folder}-${base}`,
      label: info.label || humanize(base),
      keywords: Array.isArray(info.keywords) ? info.keywords : [],
      hasFill: fills.has(base)
    };
  });
}

function renderJs(folder, category, icons) {
  const items = icons.map((icon) => {
    const alternatives = icon.hasFill ? "['fill']" : '[]';
    return (
      `    { filename: ${JSON.stringify(icon.filename)}, ` +
      `label: ${JSON.stringify(icon.label)}, ` +
      `keywords: ${JSON.stringify(icon.keywords)}, ` +
      `alternatives: ${alternatives} }`
    );
  });

  const body = items.length ? `\n${items.join(',\n')}\n  ` : '';

  return `// GENERATED by scripts/build-icons.mjs — do not edit by hand.
// Source: assets/icons/${folder}/*.svg (+ config/icons.js)
export const themeIconCategory = {
  slug: ${JSON.stringify(category.slug)},
  label: ${JSON.stringify(category.label)},
  icons: [${body}]
};
`;
}

function renderScss(folder, icons) {
  const lines = [];

  for (const icon of icons) {
    lines.push(
      `@include fs-icon-entry('${icon.class}', '../icons/${folder}/${icon.base}.svg');`
    );

    if (icon.hasFill) {
      lines.push(
        `@include fs-icon-entry('${icon.class}-fill', '../icons/${folder}/${icon.base}-fill.svg');`
      );
    }
  }

  const body = lines.length ? `\n${lines.join('\n')}\n` : '\n';

  return `// GENERATED by scripts/build-icons.mjs — do not edit by hand.
// Source: assets/icons/${folder}/*.svg (+ config/icons.js)
@use 'icons' as *;
${body}`;
}

async function build() {
  const config = await loadConfig();
  const folder = config.folder || 'theme';
  const category = config.category || { slug: folder, label: humanize(folder) };
  const meta = config.meta || {};

  const folderAbs = path.join(themeRoot, 'assets/icons', folder);
  const icons = collectIcons(folderAbs, folder, meta);

  writeFileSync(generatedJsPath, renderJs(folder, category, icons));
  writeFileSync(generatedScssPath, renderScss(folder, icons));

  console.log(
    `\u2714 icons: generated ${icons.length} theme icon(s) from assets/icons/${folder}/`
  );
}

await build();
